import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'sw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.programs': 'Programs',
    'nav.projects': 'Projects',
    'nav.impact': 'Impact Stories',
    'nav.news': 'News',
    'nav.team': 'Team',
    'nav.partners': 'Partners',
    'nav.get_involved': 'Get Involved',
    'nav.getInvolved': 'Get Involved',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.updates': 'Updates',
    'nav.donate': 'Donate Now',
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.swahili': 'Kiswahili',
    // Hero
    'hero.title': 'Empowering Communities in Eastern DR Congo',
    'hero.subtitle': 'Building a future where children thrive, women lead, and communities prosper',
    'hero.cta_donate': 'Support Our Mission',
    'hero.cta_learn': 'Learn More',
    'hero.cta1': 'Support Our Mission',
    'hero.cta2': 'Learn More',
    // Stats
    'stats.beneficiaries': 'Beneficiaries Reached',
    'stats.beneficiaries_count': '150,000+',
    'stats.regions': 'Operational Regions',
    'stats.regions_count': '12',
    'stats.programs': 'Active Programs',
    'stats.programs_count': '18',
    'stats.years': 'Years of Service',
    'stats.years_count': '15+',
    'home.stats.beneficiaries': 'Beneficiaries Reached',
    'home.stats.regions': 'Regions Served',
    'home.stats.programs': 'Active Programs',
    'home.stats.partners': 'Partners',
    'home.featuredProjects': 'Featured Projects',
    'home.testimonials': 'Stories of Impact',
    'home.partners': 'Our Partners',
    'home.latestNews': 'Latest Updates',
    // Mission
    'mission.title': 'Our Mission',
    'mission.text': 'Let Us Live Association (LULA) works to protect children, empower women, and strengthen communities in Eastern DR Congo through comprehensive programs in health education, HIV prevention, and sustainable development.',
    // Common
    'common.learn_more': 'Learn More',
    'common.learnMore': 'Learn More',
    'common.read_more': 'Read More',
    'common.readMore': 'Read More',
    'common.donate': 'Donate',
    'common.volunteer': 'Volunteer',
    'common.partner': 'Become a Partner',
    'common.getInvolved': 'Get Involved',
    'common.submit': 'Submit',
    'common.download': 'Download',
    'common.ourMission': 'Our Mission',
    'common.ourVision': 'Our Vision',
    'common.ourValues': 'Our Values',
    // About
    'about.title': 'About Let Us Live Association',
    'about.story_title': 'Our Story',
    'about.mission_title': 'Mission',
    'about.vision_title': 'Vision',
    'about.values_title': 'Core Values',
    'about.timeline_title': 'Our Journey',
    // Programs
    'programs.title': 'Our Programs',
    'programs.hiv_title': 'HIV Prevention',
    'programs.hiv_desc': 'Comprehensive HIV testing, treatment support, and community awareness programs',
    'programs.srh_title': 'Sexual & Reproductive Health',
    'programs.srh_desc': 'Education and services promoting reproductive health and family planning',
    'programs.women_title': 'Women Empowerment',
    'programs.women_desc': 'Economic empowerment and leadership development for women',
    'programs.child_title': 'Child Protection',
    'programs.child_desc': "Safeguarding children's rights and providing protective services",
    'programs.peace_title': 'Peacebuilding',
    'programs.peace_desc': 'Community reconciliation and conflict resolution initiatives',
    'programs.health_title': 'Community Health',
    'programs.health_desc': 'Primary healthcare services and health education programs',
    'programs.training_title': 'Vocational Training',
    'programs.training_desc': 'Skills development and job creation programs',
    // Projects
    'projects.title': 'Our Projects',
    'projects.all': 'All Projects',
    'projects.active': 'Active',
    'projects.completed': 'Completed',
    'projects.upcoming': 'Upcoming',
    'projects.filter': 'Filter by:',
    // Impact
    'impact.title': 'Impact Stories',
    'impact.subtitle': 'Real stories from the communities we serve',
    // Contact
    'contact.title': 'Get in Touch',
    'contact.name': 'Full Name',
    'contact.email': 'Email Address',
    'contact.phone': 'Phone Number',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.office': 'Our Office',
    // Get Involved
    'involved.title': 'Get Involved',
    'involved.donate_title': 'Make a Donation',
    'involved.volunteer_title': 'Volunteer With Us',
    'involved.partner_title': 'Partner With Us',
    // Map
    'map.title': 'Eastern DR Congo - Our Operational Provinces',
    'map.regions_header': 'Our all 12 regions',
    // Footer
    'footer.about': 'About LULA',
    'footer.aboutUs': 'About LULA',
    'footer.description': 'Let Us Live Association (LULA) is a humanitarian NGO dedicated to empowering vulnerable communities in Eastern Democratic Republic of Congo.',
    'footer.quick_links': 'Quick Links',
    'footer.quickLinks': 'Quick Links',
    'footer.programs': 'Our Programs',
    'footer.contact_us': 'Contact Us',
    'footer.getInTouch': 'Get In Touch',
    'footer.address': 'Goma, North Kivu, DR Congo',
    'footer.email': 'info@lulacongo.org',
    'footer.phone': '+243 XXX XXX XXX',
    'footer.follow': 'Follow Us',
    'footer.copyright': '© 2025 Let Us Live Association. All rights reserved.',
    'footer.rights': '© 2025 Let Us Live Association (LULA). All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    // Homepage sections
    'home.mission.heading': 'Empowering Communities, Transforming Lives',
    'home.mission.text': 'LULA works to create lasting change in Eastern Democratic Republic of Congo by addressing the root causes of vulnerability through child protection, women\'s empowerment, health education, and sustainable community development.',
    'home.projects.subtitle': 'Making a real impact in communities across Eastern DRC',
    'home.impact.subtitle': 'Real stories from the communities we serve',
    'home.news.subtitle': 'Stay informed about our impact and initiatives',
    'home.cta.title': 'Join Us in Making a Difference',
    'home.cta.text': 'Your support can transform lives and build stronger, more resilient communities in Eastern DRC.',
    'home.cta.donate': 'Donate Now',
    'home.cta.volunteer': 'Become a Volunteer',
    'home.viewAllProjects': 'View All Projects',
    'home.viewImpact': 'View the changes we\'re making',
    'home.viewAllNews': 'View All News & Publications',
    // Projects page
    'projects.subtitle': 'Transforming lives through targeted interventions across Eastern DR Congo',
    'projects.viewDetails': 'View Details',
    'projects.volunteer': 'Volunteer',
    // Programs page
    'programs.subtitle': 'Comprehensive programs addressing the most critical needs in Eastern DR Congo',
    'programs.supportIt': 'Support It',
    // About page
    'about.heroSubtitle': 'Building a brighter future for Eastern DR Congo, one community at a time',
    'about.valuesSubtitle': 'The principles that guide our work every day',
    'about.journey': 'Our Journey',
    'about.journeySubtitle': 'Milestones of impact and growth',
    'about.whereWeWork': 'Where We Work',
    'about.whereWeWorkSubtitle': 'Operating across 12 regions in Eastern DRC',
    // Contact page
    'contact.subtitle': 'We\'d love to hear from you. Reach out to learn more about our work or get involved.',
    'contact.sendMessage': 'Send Us a Message',
    'contact.headOffice': 'Head Office',
    'contact.officeHours': 'Office Hours',
    'contact.responseTime': 'We respond within 24 hours',
    'contact.successTitle': 'Message Sent Successfully!',
    'contact.successText': 'Thank you for contacting us. We\'ll get back to you within 24 hours.',
    // Get Involved page
    'involved.subtitle': 'Your support transforms lives and builds stronger communities in Eastern DR Congo',
    'involved.selectAmount': 'Select Amount',
    'involved.customAmount': 'Or Enter Custom Amount',
    'involved.yourImpact': 'Your Impact',
    'involved.applyVolunteer': 'Apply to Volunteer',
    'involved.partnerInquiry': 'Partnership Inquiry',
    // Team page
    'team.title': 'Our Team',
    'team.subtitle': 'Dedicated professionals committed to transforming lives in Eastern DR Congo',
    'team.leadership': 'Executive Leadership',
    'team.leadershipSubtitle': 'Experienced leaders guiding our mission and strategic direction',
    'team.staff': 'Our Team',
    'team.staffSubtitle': 'Passionate professionals working on the ground to deliver impact',
    'team.joinTitle': 'Join Our Team',
    'team.joinText': 'We\'re always looking for passionate individuals to join our mission',
    'team.viewPositions': 'View Open Positions',
    // Partners page
    'partners.title': 'Our Partners',
    'partners.subtitle': 'Collaborating with organizations worldwide to maximize impact in Eastern DR Congo',
    'partners.become': 'Become a Partner',
    'partners.becomeText': 'Join us in creating lasting impact for communities in Eastern DR Congo',
    'partners.partnerWithUs': 'Partner With Us',
    // Forms & labels
    'form.name': 'Name',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.message': 'Message',
    'form.submit': 'Submit',
    'form.cancel': 'Cancel',
    'form.quickSelect': 'Quick Select Amount',
    'form.orEnterAmount': 'Or Enter Amount',
    'form.currency': 'Currency',
    'form.donateVia': 'Donate via WhatsApp',
    'form.paymentDetails': 'Payment Details',
    'form.volunteerApp': 'Volunteer Application',
    'form.volunteerAppDesc': 'Please fill out the form below to apply to volunteer with us.',
    'form.partnerInquiry': 'Partnership Inquiry',
    'form.partnerInquiryDesc': 'Please fill out the form below to inquire about partnering with us.',
    'form.donateTitle': 'Donate',
    'form.donateDesc': 'Please fill out the form below to donate to our cause.',
    'form.thankYouVolunteer': 'Thank You for Volunteering!',
    'form.thankYouPartner': 'Thank You for Your Interest!',
    'form.thankYouDonate': 'Thank You for Your Donation!',
    'form.whatsapp': 'WhatsApp',
    'form.ok': 'OK',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.programs': 'Programmes',
    'nav.projects': 'Projets',
    'nav.impact': "Histoires d'Impact",
    'nav.news': 'Actualités',
    'nav.team': 'Équipe',
    'nav.partners': 'Partenaires',
    'nav.get_involved': "S'Impliquer",
    'nav.getInvolved': "S'Impliquer",
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.updates': 'Actualités',
    'nav.donate': 'Faire un Don',
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.swahili': 'Kiswahili',
    // Hero
    'hero.title': "Autonomiser les Communautés dans l'Est de la RDC",
    'hero.subtitle': 'Construire un avenir où les enfants prospèrent, les femmes dirigent et les communautés prospèrent',
    'hero.cta_donate': 'Soutenir Notre Mission',
    'hero.cta_learn': 'En Savoir Plus',
    'hero.cta1': 'Soutenir Notre Mission',
    'hero.cta2': 'En Savoir Plus',
    // Stats
    'stats.beneficiaries': 'Bénéficiaires Atteints',
    'stats.beneficiaries_count': '150 000+',
    'stats.regions': 'Régions Opérationnelles',
    'stats.regions_count': '12',
    'stats.programs': 'Programmes Actifs',
    'stats.programs_count': '18',
    'stats.years': 'Années de Service',
    'stats.years_count': '15+',
    'home.stats.beneficiaries': 'Bénéficiaires Atteints',
    'home.stats.regions': 'Régions Desservies',
    'home.stats.programs': 'Programmes Actifs',
    'home.stats.partners': 'Partenaires',
    'home.featuredProjects': 'Projets en Vedette',
    'home.testimonials': "Histoires d'Impact",
    'home.partners': 'Nos Partenaires',
    'home.latestNews': 'Dernières Nouvelles',
    // Mission
    'mission.title': 'Notre Mission',
    'mission.text': "L'Association Let Us Live (LULA) œuvre pour protéger les enfants, autonomiser les femmes et renforcer les communautés dans l'Est de la RD Congo à travers des programmes complets en éducation sanitaire, prévention du VIH et développement durable.",
    // Common
    'common.learn_more': 'En Savoir Plus',
    'common.learnMore': 'En Savoir Plus',
    'common.read_more': 'Lire Plus',
    'common.readMore': 'Lire la Suite',
    'common.donate': 'Faire un Don',
    'common.volunteer': 'Devenir Volontaire',
    'common.partner': 'Devenir Partenaire',
    'common.getInvolved': "S'Impliquer",
    'common.submit': 'Soumettre',
    'common.download': 'Télécharger',
    'common.ourMission': 'Notre Mission',
    'common.ourVision': 'Notre Vision',
    'common.ourValues': 'Nos Valeurs',
    // About
    'about.title': "À Propos de l'Association Let Us Live",
    'about.story_title': 'Notre Histoire',
    'about.mission_title': 'Mission',
    'about.vision_title': 'Vision',
    'about.values_title': 'Valeurs Fondamentales',
    'about.timeline_title': 'Notre Parcours',
    // Programs
    'programs.title': 'Nos Programmes',
    'programs.hiv_title': 'Prévention du VIH',
    'programs.hiv_desc': 'Tests VIH complets, soutien au traitement et programmes de sensibilisation communautaire',
    'programs.srh_title': 'Santé Sexuelle et Reproductive',
    'programs.srh_desc': 'Éducation et services promouvant la santé reproductive et la planification familiale',
    'programs.women_title': 'Autonomisation des Femmes',
    'programs.women_desc': 'Autonomisation économique et développement du leadership pour les femmes',
    'programs.child_title': "Protection de l'Enfance",
    'programs.child_desc': 'Sauvegarde des droits des enfants et fourniture de services de protection',
    'programs.peace_title': 'Consolidation de la Paix',
    'programs.peace_desc': 'Réconciliation communautaire et initiatives de résolution des conflits',
    'programs.health_title': 'Santé Communautaire',
    'programs.health_desc': "Services de soins de santé primaires et programmes d'éducation sanitaire",
    'programs.training_title': 'Formation Professionnelle',
    'programs.training_desc': "Développement des compétences et programmes de création d'emplois",
    // Projects
    'projects.title': 'Nos Projets',
    'projects.all': 'Tous les Projets',
    'projects.active': 'Actifs',
    'projects.completed': 'Complétés',
    'projects.upcoming': 'À Venir',
    'projects.filter': 'Filtrer par:',
    // Impact
    'impact.title': "Histoires d'Impact",
    'impact.subtitle': 'Histoires réelles des communautés que nous servons',
    // Contact
    'contact.title': 'Contactez-Nous',
    'contact.name': 'Nom Complet',
    'contact.email': 'Adresse Email',
    'contact.phone': 'Numéro de Téléphone',
    'contact.subject': 'Sujet',
    'contact.message': 'Message',
    'contact.send': 'Envoyer le Message',
    'contact.office': 'Notre Bureau',
    // Get Involved
    'involved.title': "S'Impliquer",
    'involved.donate_title': 'Faire un Don',
    'involved.volunteer_title': 'Devenir Volontaire',
    'involved.partner_title': 'Devenir Partenaire',
    // Map
    'map.title': 'Est de la RD Congo - Nos Provinces Opérationnelles',
    'map.regions_header': 'Nos 12 régions',
    // Footer
    'footer.about': 'À Propos de LULA',
    'footer.aboutUs': 'À Propos de LULA',
    'footer.description': "Let Us Live Association (LULA) est une ONG humanitaire dédiée à l'autonomisation des communautés vulnérables dans l'Est de la République Démocratique du Congo.",
    'footer.quick_links': 'Liens Rapides',
    'footer.quickLinks': 'Liens Rapides',
    'footer.programs': 'Programmes',
    'footer.contact_us': 'Contactez-Nous',
    'footer.getInTouch': 'Contactez-nous',
    'footer.address': 'Goma, Nord-Kivu, RD Congo',
    'footer.email': 'info@lulacongo.org',
    'footer.phone': '+243 XXX XXX XXX',
    'footer.follow': 'Suivez-Nous',
    'footer.copyright': '© 2025 Association Let Us Live. Tous droits réservés.',
    'footer.rights': '© 2025 Let Us Live Association (LULA). Tous droits réservés.',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': "Conditions d'Utilisation",
    // Homepage sections
    'home.mission.heading': 'Autonomiser les Communautés, Transformer les Vies',
    'home.mission.text': 'LULA œuvre pour créer un changement durable en République Démocratique du Congo en s\'attaquant aux causes profondes de la vulnérabilité à travers la protection des enfants, l\'autonomisation des femmes, l\'éducation sanitaire et le développement communautaire durable.',
    'home.projects.subtitle': 'Un impact réel dans les communautés de l\'Est de la RDC',
    'home.impact.subtitle': 'Histoires réelles des communautés que nous servons',
    'home.news.subtitle': 'Restez informé de notre impact et de nos initiatives',
    'home.cta.title': 'Rejoignez-nous pour Faire la Différence',
    'home.cta.text': 'Votre soutien peut transformer des vies et construire des communautés plus fortes et résilientes dans l\'Est de la RDC.',
    'home.cta.donate': 'Faire un Don',
    'home.cta.volunteer': 'Devenir Volontaire',
    'home.viewAllProjects': 'Voir Tous les Projets',
    'home.viewImpact': 'Voir les changements que nous apportons',
    'home.viewAllNews': 'Voir Toutes les Actualités',
    // Projects page
    'projects.subtitle': 'Transformer des vies grâce à des interventions ciblées dans l\'Est de la RDC',
    'projects.viewDetails': 'Voir les Détails',
    'projects.volunteer': 'Volontaire',
    // Programs page
    'programs.subtitle': 'Des programmes complets répondant aux besoins les plus critiques dans l\'Est de la RDC',
    'programs.supportIt': 'Soutenir',
    // About page
    'about.heroSubtitle': 'Construire un avenir meilleur pour l\'Est de la RDC, une communauté à la fois',
    'about.valuesSubtitle': 'Les principes qui guident notre travail chaque jour',
    'about.journey': 'Notre Parcours',
    'about.journeySubtitle': 'Jalons d\'impact et de croissance',
    'about.whereWeWork': 'Où Nous Travaillons',
    'about.whereWeWorkSubtitle': 'Opérant dans 12 régions de l\'Est de la RDC',
    // Contact page
    'contact.subtitle': 'Nous serions ravis de vous entendre. Contactez-nous pour en savoir plus sur notre travail.',
    'contact.sendMessage': 'Envoyez-nous un Message',
    'contact.headOffice': 'Siège Social',
    'contact.officeHours': 'Heures d\'Ouverture',
    'contact.responseTime': 'Nous répondons dans les 24 heures',
    'contact.successTitle': 'Message Envoyé avec Succès!',
    'contact.successText': 'Merci de nous avoir contactés. Nous vous répondrons dans les 24 heures.',
    // Get Involved page
    'involved.subtitle': 'Votre soutien transforme des vies et construit des communautés plus fortes dans l\'Est de la RDC',
    'involved.selectAmount': 'Sélectionner un Montant',
    'involved.customAmount': 'Ou Entrer un Montant Personnalisé',
    'involved.yourImpact': 'Votre Impact',
    'involved.applyVolunteer': 'Postuler comme Volontaire',
    'involved.partnerInquiry': 'Demande de Partenariat',
    // Team page
    'team.title': 'Notre Équipe',
    'team.subtitle': 'Des professionnels dévoués engagés à transformer des vies dans l\'Est de la RDC',
    'team.leadership': 'Direction Exécutive',
    'team.leadershipSubtitle': 'Des leaders expérimentés guidant notre mission et notre direction stratégique',
    'team.staff': 'Notre Équipe',
    'team.staffSubtitle': 'Des professionnels passionnés travaillant sur le terrain pour créer un impact',
    'team.joinTitle': 'Rejoignez Notre Équipe',
    'team.joinText': 'Nous recherchons toujours des personnes passionnées pour rejoindre notre mission',
    'team.viewPositions': 'Voir les Postes Ouverts',
    // Partners page
    'partners.title': 'Nos Partenaires',
    'partners.subtitle': 'Collaborer avec des organisations du monde entier pour maximiser l\'impact dans l\'Est de la RDC',
    'partners.become': 'Devenir Partenaire',
    'partners.becomeText': 'Rejoignez-nous pour créer un impact durable pour les communautés de l\'Est de la RDC',
    'partners.partnerWithUs': 'Devenir Partenaire',
    // Forms & labels
    'form.name': 'Nom',
    'form.email': 'Email',
    'form.phone': 'T\u00e9l\u00e9phone',
    'form.message': 'Message',
    'form.submit': 'Soumettre',
    'form.cancel': 'Annuler',
    'form.quickSelect': 'S\u00e9lection Rapide du Montant',
    'form.orEnterAmount': 'Ou Entrer un Montant',
    'form.currency': 'Devise',
    'form.donateVia': 'Faire un Don via WhatsApp',
    'form.paymentDetails': 'D\u00e9tails de Paiement',
    'form.volunteerApp': 'Candidature B\u00e9n\u00e9vole',
    'form.volunteerAppDesc': 'Veuillez remplir le formulaire ci-dessous pour postuler comme b\u00e9n\u00e9vole.',
    'form.partnerInquiry': 'Demande de Partenariat',
    'form.partnerInquiryDesc': 'Veuillez remplir le formulaire ci-dessous pour devenir partenaire.',
    'form.donateTitle': 'Faire un Don',
    'form.donateDesc': 'Veuillez remplir le formulaire ci-dessous pour faire un don.',
    'form.thankYouVolunteer': 'Merci pour votre candidature!',
    'form.thankYouPartner': 'Merci pour votre int\u00e9r\u00eat!',
    'form.thankYouDonate': 'Merci pour votre don!',
    'form.whatsapp': 'WhatsApp',
    'form.ok': 'OK',
  },
  sw: {
    // Navigation
    'nav.home': 'Nyumbani',
    'nav.about': 'Kuhusu Sisi',
    'nav.programs': 'Programu',
    'nav.projects': 'Miradi',
    'nav.impact': 'Hadithi za Athari',
    'nav.news': 'Habari',
    'nav.team': 'Timu',
    'nav.partners': 'Washirika',
    'nav.get_involved': 'Jiunge Nasi',
    'nav.getInvolved': 'Jiunga Nasi',
    'nav.contact': 'Wasiliana',
    'nav.admin': 'Msimamizi',
    'nav.updates': 'Habari',
    'nav.donate': 'Toa Mchango',
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.swahili': 'Kiswahili',
    // Hero
    'hero.title': 'Kuwezesha Jamii Mashariki mwa DR Congo',
    'hero.subtitle': 'Kujenga mustakabali ambapo watoto wanastawi, wanawake wanaongoza, na jamii zinafanikiwa',
    'hero.cta_donate': 'Unga Mkono Dhamira Yetu',
    'hero.cta_learn': 'Jifunze Zaidi',
    'hero.cta1': 'Unga Mkono Dhamira Yetu',
    'hero.cta2': 'Jifunze Zaidi',
    // Stats
    'stats.beneficiaries': 'Wanufaika Waliofikwa',
    'stats.beneficiaries_count': '150,000+',
    'stats.regions': 'Mikoa ya Uendeshaji',
    'stats.regions_count': '12',
    'stats.programs': 'Programu Zinazoendelea',
    'stats.programs_count': '18',
    'stats.years': 'Miaka ya Huduma',
    'stats.years_count': '15+',
    'home.stats.beneficiaries': 'Wanufaika Waliofikia',
    'home.stats.regions': 'Mikoa Inayotumikia',
    'home.stats.programs': 'Programu Zinazoendelea',
    'home.stats.partners': 'Washirika',
    'home.featuredProjects': 'Miradi Iliyoangaliwa',
    'home.testimonials': 'Hadithi za Athari',
    'home.partners': 'Washirika Wetu',
    'home.latestNews': 'Habari za Hivi Karibuni',
    // Mission
    'mission.title': 'Dhamira Yetu',
    'mission.text': 'Shirika la Let Us Live (LULA) linafanya kazi kulinda watoto, kuwezesha wanawake, na kuimarisha jamii Mashariki mwa DR Congo kupitia programu kamili za elimu ya afya, kuzuia VVU, na maendeleo endelevu.',
    // Common
    'common.learn_more': 'Jifunze Zaidi',
    'common.learnMore': 'Jifunze Zaidi',
    'common.read_more': 'Soma Zaidi',
    'common.readMore': 'Soma Zaidi',
    'common.donate': 'Toa Mchango',
    'common.volunteer': 'Jitolee',
    'common.partner': 'Kuwa Mshirika',
    'common.getInvolved': 'Jiunga Nasi',
    'common.submit': 'Wasilisha',
    'common.download': 'Pakua',
    'common.ourMission': 'Dhamira Yetu',
    'common.ourVision': 'Maono Yetu',
    'common.ourValues': 'Maadili Yetu',
    // About
    'about.title': 'Kuhusu Shirika la Let Us Live',
    'about.story_title': 'Hadithi Yetu',
    'about.mission_title': 'Dhamira',
    'about.vision_title': 'Maono',
    'about.values_title': 'Maadili Muhimu',
    'about.timeline_title': 'Safari Yetu',
    // Programs
    'programs.title': 'Programu Zetu',
    'programs.hiv_title': 'Kuzuia VVU',
    'programs.hiv_desc': 'Vipimo vya VVU, msaada wa matibabu, na programu za ufahamu wa jamii',
    'programs.srh_title': 'Afya ya Uzazi na Kijinsia',
    'programs.srh_desc': 'Elimu na huduma zinazoendeleza afya ya uzazi na mipango ya familia',
    'programs.women_title': 'Uwezeshaji wa Wanawake',
    'programs.women_desc': 'Uwezeshaji wa kiuchumi na maendeleo ya uongozi kwa wanawake',
    'programs.child_title': 'Ulinzi wa Watoto',
    'programs.child_desc': 'Kulinda haki za watoto na kutoa huduma za ulinzi',
    'programs.peace_title': 'Kujenga Amani',
    'programs.peace_desc': 'Upatanisho wa jamii na mipango ya kusuluhisha migogoro',
    'programs.health_title': 'Afya ya Jamii',
    'programs.health_desc': 'Huduma za afya ya msingi na programu za elimu ya afya',
    'programs.training_title': 'Mafunzo ya Ufundi',
    'programs.training_desc': 'Maendeleo ya ujuzi na programu za kuunda ajira',
    // Projects
    'projects.title': 'Miradi Yetu',
    'projects.all': 'Miradi Yote',
    'projects.active': 'Inaendelea',
    'projects.completed': 'Iliyokamilika',
    'projects.upcoming': 'Inayokuja',
    'projects.filter': 'Chuja kwa:',
    // Impact
    'impact.title': 'Hadithi za Athari',
    'impact.subtitle': 'Hadithi halisi kutoka jamii tunazozihudumia',
    // Contact
    'contact.title': 'Wasiliana Nasi',
    'contact.name': 'Jina Kamili',
    'contact.email': 'Barua Pepe',
    'contact.phone': 'Nambari ya Simu',
    'contact.subject': 'Mada',
    'contact.message': 'Ujumbe',
    'contact.send': 'Tuma Ujumbe',
    'contact.office': 'Ofisi Yetu',
    // Get Involved
    'involved.title': 'Jiunge Nasi',
    'involved.donate_title': 'Toa Mchango',
    'involved.volunteer_title': 'Jitolee',
    'involved.partner_title': 'Kuwa Mshirika',
    // Map
    'map.title': 'Mashariki mwa DR Congo - Mikoa Yetu ya Uendeshaji',
    'map.regions_header': 'Mikoa yetu 12 yote',
    // Footer
    'footer.about': 'Kuhusu LULA',
    'footer.aboutUs': 'Kuhusu LULA',
    'footer.description': 'Let Us Live Association (LULA) ni NGO ya kibinadamu inayojitahidi kuwezesha jamii zilizo hatarini katika Mashariki mwa Jamhuri ya Kidemokrasia ya Congo.',
    'footer.quick_links': 'Viungo vya Haraka',
    'footer.quickLinks': 'Viungo vya Haraka',
    'footer.programs': 'Programu Zetu',
    'footer.contact_us': 'Wasiliana Nasi',
    'footer.getInTouch': 'Wasiliana Nasi',
    'footer.address': 'Goma, Kivu Kaskazini, DR Congo',
    'footer.email': 'info@lulacongo.org',
    'footer.phone': '+243 XXX XXX XXX',
    'footer.follow': 'Tufuate',
    'footer.copyright': '© 2025 Shirika la Let Us Live. Haki zote zimehifadhiwa.',
    'footer.rights': '© 2025 Let Us Live Association (LULA). Haki zote zimehifadhiwa.',
    'footer.privacy': 'Sera ya Faragha',
    'footer.terms': 'Masharti ya Huduma',
    // Homepage sections
    'home.mission.heading': 'Kuwezesha Jamii, Kubadilisha Maisha',
    'home.mission.text': 'LULA inafanya kazi kuunda mabadiliko ya kudumu katika Mashariki mwa Jamhuri ya Kidemokrasia ya Congo kwa kushughulikia sababu za msingi za udhaifu kupitia ulinzi wa watoto, uwezeshaji wa wanawake, elimu ya afya, na maendeleo endelevu ya jamii.',
    'home.projects.subtitle': 'Athari halisi katika jamii za Mashariki mwa DRC',
    'home.impact.subtitle': 'Hadithi halisi kutoka jamii tunazozihudumia',
    'home.news.subtitle': 'Endelea kupata habari kuhusu athari na mipango yetu',
    'home.cta.title': 'Jiunge Nasi Kuleta Mabadiliko',
    'home.cta.text': 'Msaada wako unaweza kubadilisha maisha na kujenga jamii imara zaidi Mashariki mwa DRC.',
    'home.cta.donate': 'Toa Mchango Sasa',
    'home.cta.volunteer': 'Kuwa Mjitolea',
    'home.viewAllProjects': 'Tazama Miradi Yote',
    'home.viewImpact': 'Tazama mabadiliko tunayoleta',
    'home.viewAllNews': 'Tazama Habari Zote',
    // Projects page
    'projects.subtitle': 'Kubadilisha maisha kupitia hatua zinazolengwa katika Mashariki mwa DRC',
    'projects.viewDetails': 'Tazama Maelezo',
    'projects.volunteer': 'Jitolee',
    // Programs page
    'programs.subtitle': 'Programu kamili zinazoshughulikia mahitaji muhimu zaidi Mashariki mwa DRC',
    'programs.supportIt': 'Unga Mkono',
    // About page
    'about.heroSubtitle': 'Kujenga mustakabali bora kwa Mashariki mwa DRC, jamii moja kwa wakati',
    'about.valuesSubtitle': 'Kanuni zinazoongoza kazi yetu kila siku',
    'about.journey': 'Safari Yetu',
    'about.journeySubtitle': 'Hatua muhimu za athari na ukuaji',
    'about.whereWeWork': 'Tunafanya Kazi Wapi',
    'about.whereWeWorkSubtitle': 'Tunafanya kazi katika mikoa 12 ya Mashariki mwa DRC',
    // Contact page
    'contact.subtitle': 'Tungependa kusikia kutoka kwako. Wasiliana nasi kujifunza zaidi kuhusu kazi yetu.',
    'contact.sendMessage': 'Tutumie Ujumbe',
    'contact.headOffice': 'Ofisi Kuu',
    'contact.officeHours': 'Masaa ya Kazi',
    'contact.responseTime': 'Tunajibu ndani ya masaa 24',
    'contact.successTitle': 'Ujumbe Umetumwa!',
    'contact.successText': 'Asante kwa kuwasiliana nasi. Tutakujibu ndani ya masaa 24.',
    // Get Involved page
    'involved.subtitle': 'Msaada wako unabadilisha maisha na kujenga jamii imara Mashariki mwa DRC',
    'involved.selectAmount': 'Chagua Kiasi',
    'involved.customAmount': 'Au Ingiza Kiasi Maalum',
    'involved.yourImpact': 'Athari Yako',
    'involved.applyVolunteer': 'Omba Kujitolea',
    'involved.partnerInquiry': 'Ombi la Ushirikiano',
    // Team page
    'team.title': 'Timu Yetu',
    'team.subtitle': 'Wataalamu waliojitolea kubadilisha maisha Mashariki mwa DRC',
    'team.leadership': 'Uongozi wa Juu',
    'team.leadershipSubtitle': 'Viongozi wenye uzoefu wanaoongoza dhamira na mwelekeo wetu',
    'team.staff': 'Timu Yetu',
    'team.staffSubtitle': 'Wataalamu wenye shauku wanaofanya kazi ardhini kuleta athari',
    'team.joinTitle': 'Jiunge na Timu Yetu',
    'team.joinText': 'Tunatafuta watu wenye shauku kujiunga na dhamira yetu',
    'team.viewPositions': 'Tazama Nafasi Zilizo Wazi',
    // Partners page
    'partners.title': 'Washirika Wetu',
    'partners.subtitle': 'Kushirikiana na mashirika duniani kote kuongeza athari Mashariki mwa DRC',
    'partners.become': 'Kuwa Mshirika',
    'partners.becomeText': 'Jiunge nasi kuunda athari ya kudumu kwa jamii za Mashariki mwa DRC',
    'partners.partnerWithUs': 'Shirikiana Nasi',
    // Forms & labels
    'form.name': 'Jina',
    'form.email': 'Barua Pepe',
    'form.phone': 'Simu',
    'form.message': 'Ujumbe',
    'form.submit': 'Wasilisha',
    'form.cancel': 'Ghairi',
    'form.quickSelect': 'Chagua Kiasi Haraka',
    'form.orEnterAmount': 'Au Ingiza Kiasi',
    'form.currency': 'Sarafu',
    'form.donateVia': 'Toa Mchango kupitia WhatsApp',
    'form.paymentDetails': 'Maelezo ya Malipo',
    'form.volunteerApp': 'Maombi ya Kujitolea',
    'form.volunteerAppDesc': 'Tafadhali jaza fomu hii kuomba kujitolea nasi.',
    'form.partnerInquiry': 'Ombi la Ushirikiano',
    'form.partnerInquiryDesc': 'Tafadhali jaza fomu hii kuomba kushirikiana nasi.',
    'form.donateTitle': 'Toa Mchango',
    'form.donateDesc': 'Tafadhali jaza fomu hii kutoa mchango.',
    'form.thankYouVolunteer': 'Asante kwa Kujitolea!',
    'form.thankYouPartner': 'Asante kwa Nia Yako!',
    'form.thankYouDonate': 'Asante kwa Mchango Wako!',
    'form.whatsapp': 'WhatsApp',
    'form.ok': 'Sawa',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      return (localStorage.getItem('lula-language') as Language) || 'en';
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('lula-language', lang);
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

// Re-export as useLULALanguage for backward compatibility
export const useLULALanguage = useLanguage;
