import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'sw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.programs': 'Programs',
    'nav.projects': 'Projects',
    'nav.impact': 'Impact Stories',
    'nav.news': 'News',
    'nav.team': 'Team',
    'nav.partners': 'Partners',
    'nav.get_involved': 'Get Involved',
    'nav.getInvolved': 'Get Involved',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.updates': 'Updates',
    'nav.donate': 'Donate Now',
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.swahili': 'Kiswahili',
    // Hero
    'hero.title': 'Empowering Communities in Eastern DR Congo',
    'hero.subtitle': 'Building a future where children thrive, women lead, and communities prosper',
    'hero.cta_donate': 'Support Our Mission',
    'hero.cta_learn': 'Learn More',
    'hero.cta1': 'Support Our Mission',
    'hero.cta2': 'Learn More',
    // Stats
    'stats.beneficiaries': 'Beneficiaries Reached',
    'stats.beneficiaries_count': '150,000+',
    'stats.regions': 'Operational Regions',
    'stats.regions_count': '12',
    'stats.programs': 'Active Programs',
    'stats.programs_count': '18',
    'stats.years': 'Years of Service',
    'stats.years_count': '15+',
    'home.stats.beneficiaries': 'Beneficiaries Reached',
    'home.stats.regions': 'Regions Served',
    'home.stats.programs': 'Active Programs',
    'home.stats.partners': 'Partners',
    'home.featuredProjects': 'Featured Projects',
    'home.testimonials': 'Stories of Impact',
    'home.partners': 'Our Partners',
    'home.latestNews': 'Latest Updates',
    // Mission
    'mission.title': 'Our Mission',
    'mission.text': 'Let Us Live Association (LULA) works to protect children, empower women, and strengthen communities in Eastern DR Congo through comprehensive programs in health education, HIV prevention, and sustainable development.',
    // Common
    'common.learn_more': 'Learn More',
    'common.learnMore': 'Learn More',
    'common.read_more': 'Read More',
    'common.readMore': 'Read More',
    'common.donate': 'Donate',
    'common.volunteer': 'Volunteer',
    'common.partner': 'Become a Partner',
    'common.getInvolved': 'Get Involved',
    'common.submit': 'Submit',
    'common.download': 'Download',
    'common.ourMission': 'Our Mission',
    'common.ourVision': 'Our Vision',
    'common.ourValues': 'Our Values',
    // About
    'about.title': 'About Let Us Live Association',
    'about.story_title': 'Our Story',
    'about.mission_title': 'Mission',
    'about.vision_title': 'Vision',
    'about.values_title': 'Core Values',
    'about.timeline_title': 'Our Journey',
    // Programs
    'programs.title': 'Our Programs',
    'programs.hiv_title': 'HIV Prevention',
    'programs.hiv_desc': 'Comprehensive HIV testing, treatment support, and community awareness programs',
    'programs.srh_title': 'Sexual & Reproductive Health',
    'programs.srh_desc': 'Education and services promoting reproductive health and family planning',
    'programs.women_title': 'Women Empowerment',
    'programs.women_desc': 'Economic empowerment and leadership development for women',
    'programs.child_title': 'Child Protection',
    'programs.child_desc': "Safeguarding children's rights and providing protective services",
    'programs.peace_title': 'Peacebuilding',
    'programs.peace_desc': 'Community reconciliation and conflict resolution initiatives',
    'programs.health_title': 'Community Health',
    'programs.health_desc': 'Primary healthcare services and health education programs',
    'programs.training_title': 'Vocational Training',
    'programs.training_desc': 'Skills development and job creation programs',
    // Projects
    'projects.title': 'Our Projects',
    'projects.all': 'All Projects',
    'projects.active': 'Active',
    'projects.completed': 'Completed',
    'projects.upcoming': 'Upcoming',
    'projects.filter': 'Filter by:',
    // Impact
    'impact.title': 'Impact Stories',
    'impact.subtitle': 'Real stories from the communities we serve',
    // Contact
    'contact.title': 'Get in Touch',
    'contact.name': 'Full Name',
    'contact.email': 'Email Address',
    'contact.phone': 'Phone Number',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.office': 'Our Office',
    // Get Involved
    'involved.title': 'Get Involved',
    'involved.donate_title': 'Make a Donation',
    'involved.volunteer_title': 'Volunteer With Us',
    'involved.partner_title': 'Partner With Us',
    // Map
    'map.title': 'Eastern DR Congo - Our Operational Provinces',
    'map.regions_header': 'Our all 12 regions',
    // Footer
    'footer.about': 'About LULA',
    'footer.aboutUs': 'About LULA',
    'footer.description': 'Let Us Live Association (LULA) is a humanitarian NGO dedicated to empowering vulnerable communities in Eastern Democratic Republic of Congo.',
    'footer.quick_links': 'Quick Links',
    'footer.quickLinks': 'Quick Links',
    'footer.programs': 'Our Programs',
    'footer.contact_us': 'Contact Us',
    'footer.getInTouch': 'Get In Touch',
    'footer.address': 'Goma, North Kivu, DR Congo',
    'footer.email': 'info@lulacongo.org',
    'footer.phone': '+243 XXX XXX XXX',
    'footer.follow': 'Follow Us',
    'footer.copyright': '© 2025 Let Us Live Association. All rights reserved.',
    'footer.rights': '© 2025 Let Us Live Association (LULA). All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    // Homepage sections
    'home.mission.heading': 'Empowering Communities, Transforming Lives',
    'home.mission.text': 'LULA works to create lasting change in Eastern Democratic Republic of Congo by addressing the root causes of vulnerability through child protection, women\'s empowerment, health education, and sustainable community development.',
    'home.projects.subtitle': 'Making a real impact in communities across Eastern DRC',
    'home.impact.subtitle': 'Real stories from the communities we serve',
    'home.news.subtitle': 'Stay informed about our impact and initiatives',
    'home.cta.title': 'Join Us in Making a Difference',
    'home.cta.text': 'Your support can transform lives and build stronger, more resilient communities in Eastern DRC.',
    'home.cta.donate': 'Donate Now',
    'home.cta.volunteer': 'Become a Volunteer',
    'home.viewAllProjects': 'View All Projects',
    'home.viewImpact': 'View the changes we\'re making',
    'home.viewAllNews': 'View All News & Publications',
    // Projects page
    'projects.subtitle': 'Transforming lives through targeted interventions across Eastern DR Congo',
    'projects.viewDetails': 'View Details',
    'projects.volunteer': 'Volunteer',
    // Programs page
    'programs.subtitle': 'Comprehensive programs addressing the most critical needs in Eastern DR Congo',
    'programs.supportIt': 'Support It',
    // About page
    'about.heroSubtitle': 'Building a brighter future for Eastern DR Congo, one community at a time',
    'about.valuesSubtitle': 'The principles that guide our work every day',
    'about.journey': 'Our Journey',
    'about.journeySubtitle': 'Milestones of impact and growth',
    'about.whereWeWork': 'Where We Work',
    'about.whereWeWorkSubtitle': 'Operating across 12 regions in Eastern DRC',
    // Contact page
    'contact.subtitle': 'We\'d love to hear from you. Reach out to learn more about our work or get involved.',
    'contact.sendMessage': 'Send Us a Message',
    'contact.headOffice': 'Head Office',
    'contact.officeHours': 'Office Hours',
    'contact.responseTime': 'We respond within 24 hours',
    'contact.successTitle': 'Message Sent Successfully!',
    'contact.successText': 'Thank you for contacting us. We\'ll get back to you within 24 hours.',
    // Get Involved page
    'involved.subtitle': 'Your support transforms lives and builds stronger communities in Eastern DR Congo',
    'involved.selectAmount': 'Select Amount',
    'involved.customAmount': 'Or Enter Custom Amount',
    'involved.yourImpact': 'Your Impact',
    'involved.applyVolunteer': 'Apply to Volunteer',
    'involved.partnerInquiry': 'Partnership Inquiry',
    // Team page
    'team.title': 'Our Team',
    'team.subtitle': 'Dedicated professionals committed to transforming lives in Eastern DR Congo',
    'team.leadership': 'Executive Leadership',
    'team.leadershipSubtitle': 'Experienced leaders guiding our mission and strategic direction',
    'team.staff': 'Our Team',
    'team.staffSubtitle': 'Passionate professionals working on the ground to deliver impact',
    'team.joinTitle': 'Join Our Team',
    'team.joinText': 'We\'re always looking for passionate individuals to join our mission',
    'team.viewPositions': 'View Open Positions',
    // Partners page
    'partners.title': 'Our Partners',
    'partners.subtitle': 'Collaborating with organizations worldwide to maximize impact in Eastern DR Congo',
    'partners.become': 'Become a Partner',
    'partners.becomeText': 'Join us in creating lasting impact for communities in Eastern DR Congo',
    'partners.partnerWithUs': 'Partner With Us',
    // Forms & labels
    'form.name': 'Name',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.message': 'Message',
    'form.submit': 'Submit',
    'form.cancel': 'Cancel',
    'form.quickSelect': 'Quick Select Amount',
    'form.orEnterAmount': 'Or Enter Amount',
    'form.currency': 'Currency',
    'form.donateVia': 'Donate via WhatsApp',
    'form.paymentDetails': 'Payment Details',
    'form.volunteerApp': 'Volunteer Application',
    'form.volunteerAppDesc': 'Please fill out the form below to apply to volunteer with us.',
    'form.partnerInquiry': 'Partnership Inquiry',
    'form.partnerInquiryDesc': 'Please fill out the form below to inquire about partnering with us.',
    'form.donateTitle': 'Donate',
    'form.donateDesc': 'Please fill out the form below to donate to our cause.',
    'form.thankYouVolunteer': 'Thank You for Volunteering!',
    'form.thankYouPartner': 'Thank You for Your Interest!',
    'form.thankYouDonate': 'Thank You for Your Donation!',
    'form.whatsapp': 'WhatsApp',
    'form.ok': 'OK',
    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.programs': 'Programs',
    'admin.projects': 'Projects',
    'admin.team': 'Team',
    'admin.partners': 'Partners',
    'admin.news': 'News & Articles',
    'admin.impactStories': 'Impact Stories',
    'admin.enquiries': 'Enquiries',
    'admin.interests': 'Interests & Donations',
    'admin.about': 'About Us Content',
    'admin.settings': 'Settings',
    'admin.exitAdmin': 'Exit Admin',
    'admin.management': 'Management Portal',
    'admin.addNew': 'Add New',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.search': 'Search',
    'admin.refresh': 'Refresh',
    'admin.noResults': 'No results found',
    'admin.confirmDelete': 'Are you sure you want to delete this?',
    'admin.programsMgmt': 'Programs Management',
    'admin.programsMgmtDesc': 'Manage your organization\'s programs',
    'admin.addProgram': 'Add Program',
    'admin.teamMgmt': 'Team Management',
    'admin.teamMgmtDesc': 'Manage your organization\'s team members',
    'admin.addTeamMember': 'Add Team Member',
    'admin.partnersMgmt': 'Partners Management',
    'admin.partnersMgmtDesc': 'Manage your organization\'s partners',
    'admin.addPartner': 'Add Partner',
    'admin.newsMgmt': 'News Management',
    'admin.newsMgmtDesc': 'Manage news and articles',
    'admin.addNews': 'Add News',
    'admin.enquiriesMgmt': 'Enquiries Management',
    'admin.enquiriesMgmtDesc': 'Manage contact form submissions',
    'admin.interestsMgmt': 'Interests & Donations',
    'admin.interestsMgmtDesc': 'Track donations, volunteers, and partners',
    'admin.impactMgmt': 'Impact Stories Management',
    'admin.impactMgmtDesc': 'Manage testimonials and impact stories',
    'admin.addStory': 'Add Impact Story',
    'admin.projectsMgmt': 'Projects Management',
    'admin.projectsMgmtDesc': 'Manage your organization\'s projects',
    'admin.addProject': 'Add Project',
    'admin.editProgram': 'Edit Program',
    'admin.addNewProgram': 'Add New Program',
    'admin.programDetails': 'Program Details',
    'admin.programTitle': 'Program Title',
    'admin.description': 'Description',
    'admin.beneficiaries': 'Beneficiaries',
    'admin.icon': 'Icon',
    'admin.publish': 'Publish',
    'admin.update': 'Update',
    'admin.discard': 'Discard Changes?',
    'admin.discardDesc': 'All unsaved progress will be lost.',
    'admin.deleteConfirm': 'Delete?',
    'admin.deleteDesc': 'This will permanently remove this item.',
    'admin.fullName': 'Full Name',
    'admin.role': 'Role/Position',
    'admin.bio': 'Bio/Description',
    'admin.location': 'Location',
    'admin.photoUrl': 'Photo URL',
    'admin.teamType': 'Team Type',
    'admin.leadership': 'Leadership',
    'admin.staff': 'Staff',
    'admin.title': 'Title',
    'admin.content': 'Content',
    'admin.imageUrl': 'Image URL',
    'admin.category': 'Category',
    'admin.region': 'Region',
    'admin.status': 'Status',
    'admin.featured': 'Featured',
    'admin.quote': 'Short Quote',
    'admin.story': 'Full Story',
    'admin.personName': 'Person\'s Name',
    'admin.personRole': 'Role/Description',
    'admin.dash.title': 'Dashboard Overview',
    'admin.dash.welcome': 'Welcome back to LULA Admin Portal',
    'admin.dash.enquiriesToday': 'Enquiries Today',
    'admin.dash.newEnquiries': 'New contact enquiries',
    'admin.dash.interestsToday': 'Interests & Donations',
    'admin.dash.volunteerPartnerDonate': 'Volunteer, partner & donation requests',
    'admin.dash.totalPrograms': 'Total Programs',
    'admin.dash.activePrograms': 'Active programs',
    'admin.dash.totalPartners': 'Total Partners',
    'admin.dash.orgPartners': 'Organization partners',
    'admin.dash.viewDetails': 'View Details',
    'admin.dash.recentContent': 'Recent Content',
    'admin.dash.noContent': 'No recent content. Start by adding projects, news, or impact stories.',
    'admin.dash.quickActions': 'Quick Actions',
    'admin.dash.addProject': 'Add Project',
    'admin.dash.addNewsArticle': 'Add News Article',
    'admin.dash.addPartner': 'Add Partner',
    'admin.dash.addImpactStory': 'Add Impact Story',
    'admin.aboutDesc': 'Edit organization mission, vision, and story',
    'admin.missionStatement': 'Mission Statement',
    'admin.missionDesc': 'Your organization core purpose and what you aim to achieve',
    'admin.visionStatement': 'Vision Statement',
    'admin.visionDesc': 'Your organization aspirational goals and future direction',
    'admin.ourStory': 'Our Story',
    'admin.storyDesc': 'Share your organization history, background, and journey',
    'admin.preview': 'Preview',
    'admin.previewDesc': 'How your content will appear on the website',
    'admin.settings.account': 'Account',
    'admin.settings.organization': 'Organization',
    'admin.settings.appearance': 'Appearance',
    'admin.settings.accountTitle': 'Account Settings',
    'admin.settings.accountDesc': 'Manage your personal account information and security',
    'admin.settings.fullName': 'Full Name',
    'admin.settings.emailAddress': 'Email Address',
    'admin.settings.changePassword': 'Change Password',
    'admin.settings.currentPassword': 'Current Password',
    'admin.settings.newPassword': 'New Password',
    'admin.settings.confirmPassword': 'Confirm New Password',
    'admin.settings.saveAccount': 'Save Account Settings',
    'admin.settings.orgTitle': 'Organization Information',
    'admin.settings.orgDesc': 'Update your organization public information',
    'admin.settings.orgName': 'Organization Name',
    'admin.settings.acronym': 'Acronym',
    'admin.settings.contactEmail': 'Contact Email',
    'admin.settings.phoneNumber': 'Phone Number',
    'admin.settings.website': 'Website',
    'admin.settings.address': 'Address',
    'admin.settings.paymentDetails': 'Payment Details (Bank, Mobile Money, etc.)',
    'admin.settings.saveOrg': 'Save Organization Settings',
    'admin.settings.bgImages': 'Background Images',
    'admin.settings.bgImagesDesc': 'Customize background images across your website',
    'admin.settings.saveBg': 'Save Background Images',
    'admin.settings.revert': 'Revert to Default',
    'admin.settings.viewLocation': 'View Location',
    'admin.settings.note': 'Changes are saved to the backend and reflect across the site immediately.',
    'about.value1.title': 'Compassion',
    'about.value1.desc': 'We lead with empathy and deep care for the communities we serve.',
    'about.value2.title': 'Integrity',
    'about.value2.desc': 'Transparency and accountability guide all our actions and decisions.',
    'about.value3.title': 'Community-Centered',
    'about.value3.desc': 'Local voices and needs drive our programs and initiatives.',
    'about.value4.title': 'Excellence',
    'about.value4.desc': 'We strive for the highest quality in everything we do.',
    'about.value5.title': 'Sustainability',
    'about.value5.desc': 'Creating long-term solutions that empower communities.',
    'about.value6.title': 'Innovation',
    'about.value6.desc': 'Embracing creative approaches to complex challenges.',
    'about.timeline1.title': 'LULA Founded',
    'about.timeline1.desc': 'Established in Goma to address urgent humanitarian needs in North Kivu.',
    'about.timeline2.title': 'First Major Partnership',
    'about.timeline2.desc': 'Partnered with UNICEF for child protection programs in refugee camps.',
    'about.timeline3.title': 'Women Empowerment Initiative',
    'about.timeline3.desc': 'Launched comprehensive vocational training programs for 5,000 women.',
    'about.timeline4.title': 'Health Education Expansion',
    'about.timeline4.desc': 'Extended HIV prevention and SRH education to 12 regions.',
    'about.timeline5.title': 'Economic Empowerment Fund',
    'about.timeline5.desc': 'Created microfinance program supporting 2,000 women-led businesses.',
    'about.timeline6.title': 'Reaching 850,000 Beneficiaries',
    'about.timeline6.desc': 'Milestone achievement with impact across Eastern DRC.',
    'news.title': 'News & Publications',
    'news.subtitle': 'Stay informed about our latest activities, impact stories, and published reports',
    'news.searchPlaceholder': 'Search news, articles, and publications...',
    'news.allCategories': 'All Categories',
    'news.noResults': 'No articles found matching your search.',
    'partners.heroTitle': 'Our Partners',
    'partners.heroSubtitle': 'Collaborating with organizations worldwide to maximize impact in Eastern DR Congo',
    'partners.international': 'International Partners',
    'partners.internationalDesc': 'Working with global organizations committed to humanitarian impact',
    'partners.government': 'Government Partners',
    'partners.governmentDesc': 'Collaborating with government entities for sustainable development',
    'partners.local': 'Local Partners',
    'partners.localDesc': 'Building strong relationships with community-based organizations',
    'partners.collaboration': 'Collaboration Areas',
    'partners.collaborationDesc': 'Strategic partnerships across multiple areas of impact',
    'partners.activePartnerships': 'Active Partnerships',
    'partners.becomeTitle': 'Become a Partner',
    'partners.becomeDesc': 'Join us in creating lasting impact for communities in Eastern DR Congo',
    'partners.cta': 'Partner With Us',
    'partners.programImpl': 'Program Implementation',
    'partners.programImplDesc': 'Joint delivery of health, education, and protection programs across Eastern DRC',
    'partners.capacityBuilding': 'Capacity Building',
    'partners.capacityDesc': 'Training and technical support to strengthen local organizations',
    'partners.research': 'Research & Advocacy',
    'partners.researchDesc': 'Collaborative research and policy advocacy for child protection',
    'partners.resource': 'Resource Mobilization',
    'partners.resourceDesc': 'Partnership for funding and resource allocation to maximize community impact',
    'involved.donateDesc': 'Your donation directly supports our programs in child protection, women empowerment, and community health.',
    'involved.volunteerDesc': 'Join our team of dedicated volunteers making a difference on the ground.',
    'involved.partnerDesc': 'Collaborate with us to amplify impact across Eastern DR Congo.',
    'involved.thankYouVolunteerDesc': 'We have received your application. Our team will contact you soon with next steps.',
    'involved.thankYouPartnerDesc': 'We have received your partnership inquiry. We will be in touch shortly.',
    'involved.thankYouDonateDesc': 'We have received your donation request. Our team will contact you with payment details.',
    'contact.whatsapp': 'Chat on WhatsApp',
    'involved.supportProject': 'Want to support this project?',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.programs': 'Programmes',
    'nav.projects': 'Projets',
    'nav.impact': "Histoires d'Impact",
    'nav.news': 'Actualités',
    'nav.team': 'Équipe',
    'nav.partners': 'Partenaires',
    'nav.get_involved': "S'Impliquer",
    'nav.getInvolved': "S'Impliquer",
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.updates': 'Actualités',
    'nav.donate': 'Faire un Don',
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.swahili': 'Kiswahili',
    // Hero
    'hero.title': "Autonomiser les Communautés dans l'Est de la RDC",
    'hero.subtitle': 'Construire un avenir où les enfants prospèrent, les femmes dirigent et les communautés prospèrent',
    'hero.cta_donate': 'Soutenir Notre Mission',
    'hero.cta_learn': 'En Savoir Plus',
    'hero.cta1': 'Soutenir Notre Mission',
    'hero.cta2': 'En Savoir Plus',
    // Stats
    'stats.beneficiaries': 'Bénéficiaires Atteints',
    'stats.beneficiaries_count': '150 000+',
    'stats.regions': 'Régions Opérationnelles',
    'stats.regions_count': '12',
    'stats.programs': 'Programmes Actifs',
    'stats.programs_count': '18',
    'stats.years': 'Années de Service',
    'stats.years_count': '15+',
    'home.stats.beneficiaries': 'Bénéficiaires Atteints',
    'home.stats.regions': 'Régions Desservies',
    'home.stats.programs': 'Programmes Actifs',
    'home.stats.partners': 'Partenaires',
    'home.featuredProjects': 'Projets en Vedette',
    'home.testimonials': "Histoires d'Impact",
    'home.partners': 'Nos Partenaires',
    'home.latestNews': 'Dernières Nouvelles',
    // Mission
    'mission.title': 'Notre Mission',
    'mission.text': "L'Association Let Us Live (LULA) œuvre pour protéger les enfants, autonomiser les femmes et renforcer les communautés dans l'Est de la RD Congo à travers des programmes complets en éducation sanitaire, prévention du VIH et développement durable.",
    // Common
    'common.learn_more': 'En Savoir Plus',
    'common.learnMore': 'En Savoir Plus',
    'common.read_more': 'Lire Plus',
    'common.readMore': 'Lire la Suite',
    'common.donate': 'Faire un Don',
    'common.volunteer': 'Devenir Volontaire',
    'common.partner': 'Devenir Partenaire',
    'common.getInvolved': "S'Impliquer",
    'common.submit': 'Soumettre',
    'common.download': 'Télécharger',
    'common.ourMission': 'Notre Mission',
    'common.ourVision': 'Notre Vision',
    'common.ourValues': 'Nos Valeurs',
    // About
    'about.title': "À Propos de l'Association Let Us Live",
    'about.story_title': 'Notre Histoire',
    'about.mission_title': 'Mission',
    'about.vision_title': 'Vision',
    'about.values_title': 'Valeurs Fondamentales',
    'about.timeline_title': 'Notre Parcours',
    // Programs
    'programs.title': 'Nos Programmes',
    'programs.hiv_title': 'Prévention du VIH',
    'programs.hiv_desc': 'Tests VIH complets, soutien au traitement et programmes de sensibilisation communautaire',
    'programs.srh_title': 'Santé Sexuelle et Reproductive',
    'programs.srh_desc': 'Éducation et services promouvant la santé reproductive et la planification familiale',
    'programs.women_title': 'Autonomisation des Femmes',
    'programs.women_desc': 'Autonomisation économique et développement du leadership pour les femmes',
    'programs.child_title': "Protection de l'Enfance",
    'programs.child_desc': 'Sauvegarde des droits des enfants et fourniture de services de protection',
    'programs.peace_title': 'Consolidation de la Paix',
    'programs.peace_desc': 'Réconciliation communautaire et initiatives de résolution des conflits',
    'programs.health_title': 'Santé Communautaire',
    'programs.health_desc': "Services de soins de santé primaires et programmes d'éducation sanitaire",
    'programs.training_title': 'Formation Professionnelle',
    'programs.training_desc': "Développement des compétences et programmes de création d'emplois",
    // Projects
    'projects.title': 'Nos Projets',
    'projects.all': 'Tous les Projets',
    'projects.active': 'Actifs',
    'projects.completed': 'Complétés',
    'projects.upcoming': 'À Venir',
    'projects.filter': 'Filtrer par:',
    // Impact
    'impact.title': "Histoires d'Impact",
    'impact.subtitle': 'Histoires réelles des communautés que nous servons',
    // Contact
    'contact.title': 'Contactez-Nous',
    'contact.name': 'Nom Complet',
    'contact.email': 'Adresse Email',
    'contact.phone': 'Numéro de Téléphone',
    'contact.subject': 'Sujet',
    'contact.message': 'Message',
    'contact.send': 'Envoyer le Message',
    'contact.office': 'Notre Bureau',
    // Get Involved
    'involved.title': "S'Impliquer",
    'involved.donate_title': 'Faire un Don',
    'involved.volunteer_title': 'Devenir Volontaire',
    'involved.partner_title': 'Devenir Partenaire',
    // Map
    'map.title': 'Est de la RD Congo - Nos Provinces Opérationnelles',
    'map.regions_header': 'Nos 12 régions',
    // Footer
    'footer.about': 'À Propos de LULA',
    'footer.aboutUs': 'À Propos de LULA',
    'footer.description': "Let Us Live Association (LULA) est une ONG humanitaire dédiée à l'autonomisation des communautés vulnérables dans l'Est de la République Démocratique du Congo.",
    'footer.quick_links': 'Liens Rapides',
    'footer.quickLinks': 'Liens Rapides',
    'footer.programs': 'Programmes',
    'footer.contact_us': 'Contactez-Nous',
    'footer.getInTouch': 'Contactez-nous',
    'footer.address': 'Goma, Nord-Kivu, RD Congo',
    'footer.email': 'info@lulacongo.org',
    'footer.phone': '+243 XXX XXX XXX',
    'footer.follow': 'Suivez-Nous',
    'footer.copyright': '© 2025 Association Let Us Live. Tous droits réservés.',
    'footer.rights': '© 2025 Let Us Live Association (LULA). Tous droits réservés.',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': "Conditions d'Utilisation",
    // Homepage sections
    'home.mission.heading': 'Autonomiser les Communautés, Transformer les Vies',
    'home.mission.text': 'LULA œuvre pour créer un changement durable en République Démocratique du Congo en s\'attaquant aux causes profondes de la vulnérabilité à travers la protection des enfants, l\'autonomisation des femmes, l\'éducation sanitaire et le développement communautaire durable.',
    'home.projects.subtitle': 'Un impact réel dans les communautés de l\'Est de la RDC',
    'home.impact.subtitle': 'Histoires réelles des communautés que nous servons',
    'home.news.subtitle': 'Restez informé de notre impact et de nos initiatives',
    'home.cta.title': 'Rejoignez-nous pour Faire la Différence',
    'home.cta.text': 'Votre soutien peut transformer des vies et construire des communautés plus fortes et résilientes dans l\'Est de la RDC.',
    'home.cta.donate': 'Faire un Don',
    'home.cta.volunteer': 'Devenir Volontaire',
    'home.viewAllProjects': 'Voir Tous les Projets',
    'home.viewImpact': 'Voir les changements que nous apportons',
    'home.viewAllNews': 'Voir Toutes les Actualités',
    // Projects page
    'projects.subtitle': 'Transformer des vies grâce à des interventions ciblées dans l\'Est de la RDC',
    'projects.viewDetails': 'Voir les Détails',
    'projects.volunteer': 'Volontaire',
    // Programs page
    'programs.subtitle': 'Des programmes complets répondant aux besoins les plus critiques dans l\'Est de la RDC',
    'programs.supportIt': 'Soutenir',
    // About page
    'about.heroSubtitle': 'Construire un avenir meilleur pour l\'Est de la RDC, une communauté à la fois',
    'about.valuesSubtitle': 'Les principes qui guident notre travail chaque jour',
    'about.journey': 'Notre Parcours',
    'about.journeySubtitle': 'Jalons d\'impact et de croissance',
    'about.whereWeWork': 'Où Nous Travaillons',
    'about.whereWeWorkSubtitle': 'Opérant dans 12 régions de l\'Est de la RDC',
    // Contact page
    'contact.subtitle': 'Nous serions ravis de vous entendre. Contactez-nous pour en savoir plus sur notre travail.',
    'contact.sendMessage': 'Envoyez-nous un Message',
    'contact.headOffice': 'Siège Social',
    'contact.officeHours': 'Heures d\'Ouverture',
    'contact.responseTime': 'Nous répondons dans les 24 heures',
    'contact.successTitle': 'Message Envoyé avec Succès!',
    'contact.successText': 'Merci de nous avoir contactés. Nous vous répondrons dans les 24 heures.',
    // Get Involved page
    'involved.subtitle': 'Votre soutien transforme des vies et construit des communautés plus fortes dans l\'Est de la RDC',
    'involved.selectAmount': 'Sélectionner un Montant',
    'involved.customAmount': 'Ou Entrer un Montant Personnalisé',
    'involved.yourImpact': 'Votre Impact',
    'involved.applyVolunteer': 'Postuler comme Volontaire',
    'involved.partnerInquiry': 'Demande de Partenariat',
    // Team page
    'team.title': 'Notre Équipe',
    'team.subtitle': 'Des professionnels dévoués engagés à transformer des vies dans l\'Est de la RDC',
    'team.leadership': 'Direction Exécutive',
    'team.leadershipSubtitle': 'Des leaders expérimentés guidant notre mission et notre direction stratégique',
    'team.staff': 'Notre Équipe',
    'team.staffSubtitle': 'Des professionnels passionnés travaillant sur le terrain pour créer un impact',
    'team.joinTitle': 'Rejoignez Notre Équipe',
    'team.joinText': 'Nous recherchons toujours des personnes passionnées pour rejoindre notre mission',
    'team.viewPositions': 'Voir les Postes Ouverts',
    // Partners page
    'partners.title': 'Nos Partenaires',
    'partners.subtitle': 'Collaborer avec des organisations du monde entier pour maximiser l\'impact dans l\'Est de la RDC',
    'partners.become': 'Devenir Partenaire',
    'partners.becomeText': 'Rejoignez-nous pour créer un impact durable pour les communautés de l\'Est de la RDC',
    'partners.partnerWithUs': 'Devenir Partenaire',
    // Forms & labels
    'form.name': 'Nom',
    'form.email': 'Email',
    'form.phone': 'T\u00e9l\u00e9phone',
    'form.message': 'Message',
    'form.submit': 'Soumettre',
    'form.cancel': 'Annuler',
    'form.quickSelect': 'S\u00e9lection Rapide du Montant',
    'form.orEnterAmount': 'Ou Entrer un Montant',
    'form.currency': 'Devise',
    'form.donateVia': 'Faire un Don via WhatsApp',
    'form.paymentDetails': 'D\u00e9tails de Paiement',
    'form.volunteerApp': 'Candidature B\u00e9n\u00e9vole',
    'form.volunteerAppDesc': 'Veuillez remplir le formulaire ci-dessous pour postuler comme b\u00e9n\u00e9vole.',
    'form.partnerInquiry': 'Demande de Partenariat',
    'form.partnerInquiryDesc': 'Veuillez remplir le formulaire ci-dessous pour devenir partenaire.',
    'form.donateTitle': 'Faire un Don',
    'form.donateDesc': 'Veuillez remplir le formulaire ci-dessous pour faire un don.',
    'form.thankYouVolunteer': 'Merci pour votre candidature!',
    'form.thankYouPartner': 'Merci pour votre int\u00e9r\u00eat!',
    'form.thankYouDonate': 'Merci pour votre don!',
    'form.whatsapp': 'WhatsApp',
    'form.ok': 'OK',
    // Admin
    'admin.dashboard': 'Tableau de Bord',
    'admin.programs': 'Programmes',
    'admin.projects': 'Projets',
    'admin.team': 'Équipe',
    'admin.partners': 'Partenaires',
    'admin.news': 'Actualités',
    'admin.impactStories': "Histoires d'Impact",
    'admin.enquiries': 'Demandes',
    'admin.interests': 'Intérêts & Dons',
    'admin.about': 'Contenu À Propos',
    'admin.settings': 'Paramètres',
    'admin.exitAdmin': 'Quitter Admin',
    'admin.management': 'Portail de Gestion',
    'admin.addNew': 'Ajouter',
    'admin.edit': 'Modifier',
    'admin.delete': 'Supprimer',
    'admin.save': 'Enregistrer',
    'admin.cancel': 'Annuler',
    'admin.search': 'Rechercher',
    'admin.refresh': 'Actualiser',
    'admin.noResults': 'Aucun résultat trouvé',
    'admin.confirmDelete': 'Êtes-vous sûr de vouloir supprimer ceci?',
    'admin.programsMgmt': 'Gestion des Programmes',
    'admin.programsMgmtDesc': 'Gérez les programmes de votre organisation',
    'admin.addProgram': 'Ajouter un Programme',
    'admin.teamMgmt': 'Gestion de l\'Équipe',
    'admin.teamMgmtDesc': 'Gérez les membres de votre équipe',
    'admin.addTeamMember': 'Ajouter un Membre',
    'admin.partnersMgmt': 'Gestion des Partenaires',
    'admin.partnersMgmtDesc': 'Gérez les partenaires de votre organisation',
    'admin.addPartner': 'Ajouter un Partenaire',
    'admin.newsMgmt': 'Gestion des Actualités',
    'admin.newsMgmtDesc': 'Gérez les actualités et articles',
    'admin.addNews': 'Ajouter une Actualité',
    'admin.enquiriesMgmt': 'Gestion des Demandes',
    'admin.enquiriesMgmtDesc': 'Gérez les soumissions du formulaire de contact',
    'admin.interestsMgmt': 'Intérêts & Dons',
    'admin.interestsMgmtDesc': 'Suivez les dons, bénévoles et partenaires',
    'admin.impactMgmt': 'Gestion des Histoires d\'Impact',
    'admin.impactMgmtDesc': 'Gérez les témoignages et histoires d\'impact',
    'admin.addStory': 'Ajouter une Histoire',
    'admin.projectsMgmt': 'Gestion des Projets',
    'admin.projectsMgmtDesc': 'Gérez les projets de votre organisation',
    'admin.addProject': 'Ajouter un Projet',
    'admin.editProgram': 'Modifier le Programme',
    'admin.addNewProgram': 'Ajouter un Programme',
    'admin.programDetails': 'D\u00e9tails du Programme',
    'admin.programTitle': 'Titre du Programme',
    'admin.description': 'Description',
    'admin.beneficiaries': 'B\u00e9n\u00e9ficiaires',
    'admin.icon': 'Ic\u00f4ne',
    'admin.publish': 'Publier',
    'admin.update': 'Mettre \u00e0 jour',
    'admin.discard': 'Annuler les modifications?',
    'admin.discardDesc': 'Tous les progr\u00e8s non enregistr\u00e9s seront perdus.',
    'admin.deleteConfirm': 'Supprimer?',
    'admin.deleteDesc': 'Cet \u00e9l\u00e9ment sera supprim\u00e9 d\u00e9finitivement.',
    'admin.fullName': 'Nom Complet',
    'admin.role': 'R\u00f4le/Poste',
    'admin.bio': 'Bio/Description',
    'admin.location': 'Localisation',
    'admin.photoUrl': 'URL de la Photo',
    'admin.teamType': 'Type d\'\'\u00c9quipe',
    'admin.leadership': 'Direction',
    'admin.staff': 'Personnel',
    'admin.title': 'Titre',
    'admin.content': 'Contenu',
    'admin.imageUrl': 'URL de l\'Image',
    'admin.category': 'Cat\u00e9gorie',
    'admin.region': 'R\u00e9gion',
    'admin.status': 'Statut',
    'admin.featured': 'En vedette',
    'admin.quote': 'Citation courte',
    'admin.story': 'Histoire compl\u00e8te',
    'admin.personName': 'Nom de la personne',
    'admin.personRole': 'R\u00f4le/Description',
    'admin.dash.title': 'Aperçu du Tableau de Bord',
    'admin.dash.welcome': 'Bienvenue sur le Portail Admin LULA',
    'admin.dash.enquiriesToday': "Demandes Aujourd'hui",
    'admin.dash.newEnquiries': 'Nouvelles demandes de contact',
    'admin.dash.interestsToday': 'Intérêts & Dons',
    'admin.dash.volunteerPartnerDonate': 'Demandes de bénévolat, partenariat et dons',
    'admin.dash.totalPrograms': 'Total Programmes',
    'admin.dash.activePrograms': 'Programmes actifs',
    'admin.dash.totalPartners': 'Total Partenaires',
    'admin.dash.orgPartners': "Partenaires de l'organisation",
    'admin.dash.viewDetails': 'Voir les Détails',
    'admin.dash.recentContent': 'Contenu Récent',
    'admin.dash.noContent': "Aucun contenu récent. Commencez par ajouter des projets ou actualités.",
    'admin.dash.quickActions': 'Actions Rapides',
    'admin.dash.addProject': 'Ajouter un Projet',
    'admin.dash.addNewsArticle': 'Ajouter une Actualité',
    'admin.dash.addPartner': 'Ajouter un Partenaire',
    'admin.dash.addImpactStory': "Ajouter une Histoire",
    'admin.aboutDesc': 'Modifier la mission, la vision et l histoire',
    'admin.missionStatement': 'Declaration de Mission',
    'admin.missionDesc': 'L objectif principal de votre organisation',
    'admin.visionStatement': 'Declaration de Vision',
    'admin.visionDesc': 'Les objectifs et la direction future de votre organisation',
    'admin.ourStory': 'Notre Histoire',
    'admin.storyDesc': 'Partagez l histoire et le parcours de votre organisation',
    'admin.preview': 'Apercu',
    'admin.previewDesc': 'Comment votre contenu apparaitra sur le site web',
    'admin.settings.account': 'Compte',
    'admin.settings.organization': 'Organisation',
    'admin.settings.appearance': 'Apparence',
    'admin.settings.accountTitle': 'Parametres du Compte',
    'admin.settings.accountDesc': 'Gerez vos informations personnelles et la securite',
    'admin.settings.fullName': 'Nom Complet',
    'admin.settings.emailAddress': 'Adresse Email',
    'admin.settings.changePassword': 'Changer le Mot de Passe',
    'admin.settings.currentPassword': 'Mot de Passe Actuel',
    'admin.settings.newPassword': 'Nouveau Mot de Passe',
    'admin.settings.confirmPassword': 'Confirmer le Mot de Passe',
    'admin.settings.saveAccount': 'Enregistrer le Compte',
    'admin.settings.orgTitle': 'Informations de l Organisation',
    'admin.settings.orgDesc': 'Mettez a jour les informations publiques de votre organisation',
    'admin.settings.orgName': 'Nom de l Organisation',
    'admin.settings.acronym': 'Acronyme',
    'admin.settings.contactEmail': 'Email de Contact',
    'admin.settings.phoneNumber': 'Numero de Telephone',
    'admin.settings.website': 'Site Web',
    'admin.settings.address': 'Adresse',
    'admin.settings.paymentDetails': 'Details de Paiement (Banque, Mobile Money, etc.)',
    'admin.settings.saveOrg': 'Enregistrer les Parametres',
    'admin.settings.bgImages': 'Images de Fond',
    'admin.settings.bgImagesDesc': 'Personnalisez les images de fond de votre site web',
    'admin.settings.saveBg': 'Enregistrer les Images',
    'admin.settings.revert': 'Retablir par Defaut',
    'admin.settings.viewLocation': 'Voir l Emplacement',
    'admin.settings.note': 'Les modifications sont enregistrees et refletees immediatement.',
    'about.value1.title': 'Compassion',
    'about.value1.desc': 'Nous agissons avec empathie et un profond souci des communautes que nous servons.',
    'about.value2.title': 'Integrite',
    'about.value2.desc': 'La transparence et la responsabilite guident toutes nos actions.',
    'about.value3.title': 'Centre sur la Communaute',
    'about.value3.desc': 'Les voix et besoins locaux orientent nos programmes et initiatives.',
    'about.value4.title': 'Excellence',
    'about.value4.desc': 'Nous visons la plus haute qualite dans tout ce que nous faisons.',
    'about.value5.title': 'Durabilite',
    'about.value5.desc': 'Creer des solutions a long terme qui autonomisent les communautes.',
    'about.value6.title': 'Innovation',
    'about.value6.desc': 'Adopter des approches creatives face aux defis complexes.',
    'about.timeline1.title': 'Fondation de LULA',
    'about.timeline1.desc': 'Creee a Goma pour repondre aux besoins humanitaires urgents au Nord-Kivu.',
    'about.timeline2.title': 'Premier Grand Partenariat',
    'about.timeline2.desc': 'Partenariat avec UNICEF pour les programmes de protection des enfants.',
    'about.timeline3.title': 'Initiative Autonomisation des Femmes',
    'about.timeline3.desc': 'Lancement de programmes de formation professionnelle pour 5 000 femmes.',
    'about.timeline4.title': 'Expansion Education Sanitaire',
    'about.timeline4.desc': 'Extension de la prevention du VIH et education SRH a 12 regions.',
    'about.timeline5.title': 'Fonds d Autonomisation Economique',
    'about.timeline5.desc': 'Creation d un programme de microfinance soutenant 2 000 entreprises.',
    'about.timeline6.title': 'Atteindre 850 000 Beneficiaires',
    'about.timeline6.desc': 'Etape importante avec un impact a travers l Est de la RDC.',
    'news.title': 'Actualites & Publications',
    'news.subtitle': 'Restez informe de nos dernieres activites, histoires d impact et rapports publies',
    'news.searchPlaceholder': 'Rechercher actualites, articles et publications...',
    'news.allCategories': 'Toutes les Categories',
    'news.noResults': 'Aucun article trouve correspondant a votre recherche.',
    'partners.heroTitle': 'Nos Partenaires',
    'partners.heroSubtitle': 'Collaborer avec des organisations du monde entier pour maximiser l impact dans l Est de la RDC',
    'partners.international': 'Partenaires Internationaux',
    'partners.internationalDesc': 'Travailler avec des organisations mondiales engagees dans l impact humanitaire',
    'partners.government': 'Partenaires Gouvernementaux',
    'partners.governmentDesc': 'Collaborer avec des entites gouvernementales pour un developpement durable',
    'partners.local': 'Partenaires Locaux',
    'partners.localDesc': 'Etablir des relations solides avec les organisations communautaires',
    'partners.collaboration': 'Domaines de Collaboration',
    'partners.collaborationDesc': 'Partenariats strategiques dans plusieurs domaines d impact',
    'partners.activePartnerships': 'Partenariats Actifs',
    'partners.becomeTitle': 'Devenir Partenaire',
    'partners.becomeDesc': 'Rejoignez-nous pour creer un impact durable pour les communautes de l Est de la RDC',
    'partners.cta': 'Devenir Partenaire',
    'partners.programImpl': 'Mise en Oeuvre des Programmes',
    'partners.programImplDesc': 'Mise en oeuvre conjointe de programmes de sante, education et protection',
    'partners.capacityBuilding': 'Renforcement des Capacites',
    'partners.capacityDesc': 'Formation et soutien technique pour renforcer les organisations locales',
    'partners.research': 'Recherche & Plaidoyer',
    'partners.researchDesc': 'Recherche collaborative et plaidoyer politique pour la protection des enfants',
    'partners.resource': 'Mobilisation des Ressources',
    'partners.resourceDesc': 'Partenariat pour le financement et l allocation des ressources',
    'involved.donateDesc': 'Votre don soutient directement nos programmes de protection des enfants, d autonomisation des femmes et de sante communautaire.',
    'involved.volunteerDesc': 'Rejoignez notre equipe de benevoles devoues qui font la difference sur le terrain.',
    'involved.partnerDesc': 'Collaborez avec nous pour amplifier l impact dans l Est de la RDC.',
    'involved.thankYouVolunteerDesc': 'Nous avons recu votre candidature. Notre equipe vous contactera bientot.',
    'involved.thankYouPartnerDesc': 'Nous avons recu votre demande de partenariat. Nous vous contacterons sous peu.',
    'involved.thankYouDonateDesc': 'Nous avons recu votre demande de don. Notre equipe vous contactera avec les details de paiement.',
    'contact.whatsapp': 'Discuter sur WhatsApp',
    'involved.supportProject': 'Vous voulez soutenir ce projet?',
  },
  sw: {
    // Navigation
    'nav.home': 'Nyumbani',
    'nav.about': 'Kuhusu Sisi',
    'nav.programs': 'Programu',
    'nav.projects': 'Miradi',
    'nav.impact': 'Hadithi za Athari',
    'nav.news': 'Habari',
    'nav.team': 'Timu',
    'nav.partners': 'Washirika',
    'nav.get_involved': 'Jiunge Nasi',
    'nav.getInvolved': 'Jiunga Nasi',
    'nav.contact': 'Wasiliana',
    'nav.admin': 'Msimamizi',
    'nav.updates': 'Habari',
    'nav.donate': 'Toa Mchango',
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.swahili': 'Kiswahili',
    // Hero
    'hero.title': 'Kuwezesha Jamii Mashariki mwa DR Congo',
    'hero.subtitle': 'Kujenga mustakabali ambapo watoto wanastawi, wanawake wanaongoza, na jamii zinafanikiwa',
    'hero.cta_donate': 'Unga Mkono Dhamira Yetu',
    'hero.cta_learn': 'Jifunze Zaidi',
    'hero.cta1': 'Unga Mkono Dhamira Yetu',
    'hero.cta2': 'Jifunze Zaidi',
    // Stats
    'stats.beneficiaries': 'Wanufaika Waliofikwa',
    'stats.beneficiaries_count': '150,000+',
    'stats.regions': 'Mikoa ya Uendeshaji',
    'stats.regions_count': '12',
    'stats.programs': 'Programu Zinazoendelea',
    'stats.programs_count': '18',
    'stats.years': 'Miaka ya Huduma',
    'stats.years_count': '15+',
    'home.stats.beneficiaries': 'Wanufaika Waliofikia',
    'home.stats.regions': 'Mikoa Inayotumikia',
    'home.stats.programs': 'Programu Zinazoendelea',
    'home.stats.partners': 'Washirika',
    'home.featuredProjects': 'Miradi Iliyoangaliwa',
    'home.testimonials': 'Hadithi za Athari',
    'home.partners': 'Washirika Wetu',
    'home.latestNews': 'Habari za Hivi Karibuni',
    // Mission
    'mission.title': 'Dhamira Yetu',
    'mission.text': 'Shirika la Let Us Live (LULA) linafanya kazi kulinda watoto, kuwezesha wanawake, na kuimarisha jamii Mashariki mwa DR Congo kupitia programu kamili za elimu ya afya, kuzuia VVU, na maendeleo endelevu.',
    // Common
    'common.learn_more': 'Jifunze Zaidi',
    'common.learnMore': 'Jifunze Zaidi',
    'common.read_more': 'Soma Zaidi',
    'common.readMore': 'Soma Zaidi',
    'common.donate': 'Toa Mchango',
    'common.volunteer': 'Jitolee',
    'common.partner': 'Kuwa Mshirika',
    'common.getInvolved': 'Jiunga Nasi',
    'common.submit': 'Wasilisha',
    'common.download': 'Pakua',
    'common.ourMission': 'Dhamira Yetu',
    'common.ourVision': 'Maono Yetu',
    'common.ourValues': 'Maadili Yetu',
    // About
    'about.title': 'Kuhusu Shirika la Let Us Live',
    'about.story_title': 'Hadithi Yetu',
    'about.mission_title': 'Dhamira',
    'about.vision_title': 'Maono',
    'about.values_title': 'Maadili Muhimu',
    'about.timeline_title': 'Safari Yetu',
    // Programs
    'programs.title': 'Programu Zetu',
    'programs.hiv_title': 'Kuzuia VVU',
    'programs.hiv_desc': 'Vipimo vya VVU, msaada wa matibabu, na programu za ufahamu wa jamii',
    'programs.srh_title': 'Afya ya Uzazi na Kijinsia',
    'programs.srh_desc': 'Elimu na huduma zinazoendeleza afya ya uzazi na mipango ya familia',
    'programs.women_title': 'Uwezeshaji wa Wanawake',
    'programs.women_desc': 'Uwezeshaji wa kiuchumi na maendeleo ya uongozi kwa wanawake',
    'programs.child_title': 'Ulinzi wa Watoto',
    'programs.child_desc': 'Kulinda haki za watoto na kutoa huduma za ulinzi',
    'programs.peace_title': 'Kujenga Amani',
    'programs.peace_desc': 'Upatanisho wa jamii na mipango ya kusuluhisha migogoro',
    'programs.health_title': 'Afya ya Jamii',
    'programs.health_desc': 'Huduma za afya ya msingi na programu za elimu ya afya',
    'programs.training_title': 'Mafunzo ya Ufundi',
    'programs.training_desc': 'Maendeleo ya ujuzi na programu za kuunda ajira',
    // Projects
    'projects.title': 'Miradi Yetu',
    'projects.all': 'Miradi Yote',
    'projects.active': 'Inaendelea',
    'projects.completed': 'Iliyokamilika',
    'projects.upcoming': 'Inayokuja',
    'projects.filter': 'Chuja kwa:',
    // Impact
    'impact.title': 'Hadithi za Athari',
    'impact.subtitle': 'Hadithi halisi kutoka jamii tunazozihudumia',
    // Contact
    'contact.title': 'Wasiliana Nasi',
    'contact.name': 'Jina Kamili',
    'contact.email': 'Barua Pepe',
    'contact.phone': 'Nambari ya Simu',
    'contact.subject': 'Mada',
    'contact.message': 'Ujumbe',
    'contact.send': 'Tuma Ujumbe',
    'contact.office': 'Ofisi Yetu',
    // Get Involved
    'involved.title': 'Jiunge Nasi',
    'involved.donate_title': 'Toa Mchango',
    'involved.volunteer_title': 'Jitolee',
    'involved.partner_title': 'Kuwa Mshirika',
    // Map
    'map.title': 'Mashariki mwa DR Congo - Mikoa Yetu ya Uendeshaji',
    'map.regions_header': 'Mikoa yetu 12 yote',
    // Footer
    'footer.about': 'Kuhusu LULA',
    'footer.aboutUs': 'Kuhusu LULA',
    'footer.description': 'Let Us Live Association (LULA) ni NGO ya kibinadamu inayojitahidi kuwezesha jamii zilizo hatarini katika Mashariki mwa Jamhuri ya Kidemokrasia ya Congo.',
    'footer.quick_links': 'Viungo vya Haraka',
    'footer.quickLinks': 'Viungo vya Haraka',
    'footer.programs': 'Programu Zetu',
    'footer.contact_us': 'Wasiliana Nasi',
    'footer.getInTouch': 'Wasiliana Nasi',
    'footer.address': 'Goma, Kivu Kaskazini, DR Congo',
    'footer.email': 'info@lulacongo.org',
    'footer.phone': '+243 XXX XXX XXX',
    'footer.follow': 'Tufuate',
    'footer.copyright': '© 2025 Shirika la Let Us Live. Haki zote zimehifadhiwa.',
    'footer.rights': '© 2025 Let Us Live Association (LULA). Haki zote zimehifadhiwa.',
    'footer.privacy': 'Sera ya Faragha',
    'footer.terms': 'Masharti ya Huduma',
    // Homepage sections
    'home.mission.heading': 'Kuwezesha Jamii, Kubadilisha Maisha',
    'home.mission.text': 'LULA inafanya kazi kuunda mabadiliko ya kudumu katika Mashariki mwa Jamhuri ya Kidemokrasia ya Congo kwa kushughulikia sababu za msingi za udhaifu kupitia ulinzi wa watoto, uwezeshaji wa wanawake, elimu ya afya, na maendeleo endelevu ya jamii.',
    'home.projects.subtitle': 'Athari halisi katika jamii za Mashariki mwa DRC',
    'home.impact.subtitle': 'Hadithi halisi kutoka jamii tunazozihudumia',
    'home.news.subtitle': 'Endelea kupata habari kuhusu athari na mipango yetu',
    'home.cta.title': 'Jiunge Nasi Kuleta Mabadiliko',
    'home.cta.text': 'Msaada wako unaweza kubadilisha maisha na kujenga jamii imara zaidi Mashariki mwa DRC.',
    'home.cta.donate': 'Toa Mchango Sasa',
    'home.cta.volunteer': 'Kuwa Mjitolea',
    'home.viewAllProjects': 'Tazama Miradi Yote',
    'home.viewImpact': 'Tazama mabadiliko tunayoleta',
    'home.viewAllNews': 'Tazama Habari Zote',
    // Projects page
    'projects.subtitle': 'Kubadilisha maisha kupitia hatua zinazolengwa katika Mashariki mwa DRC',
    'projects.viewDetails': 'Tazama Maelezo',
    'projects.volunteer': 'Jitolee',
    // Programs page
    'programs.subtitle': 'Programu kamili zinazoshughulikia mahitaji muhimu zaidi Mashariki mwa DRC',
    'programs.supportIt': 'Unga Mkono',
    // About page
    'about.heroSubtitle': 'Kujenga mustakabali bora kwa Mashariki mwa DRC, jamii moja kwa wakati',
    'about.valuesSubtitle': 'Kanuni zinazoongoza kazi yetu kila siku',
    'about.journey': 'Safari Yetu',
    'about.journeySubtitle': 'Hatua muhimu za athari na ukuaji',
    'about.whereWeWork': 'Tunafanya Kazi Wapi',
    'about.whereWeWorkSubtitle': 'Tunafanya kazi katika mikoa 12 ya Mashariki mwa DRC',
    // Contact page
    'contact.subtitle': 'Tungependa kusikia kutoka kwako. Wasiliana nasi kujifunza zaidi kuhusu kazi yetu.',
    'contact.sendMessage': 'Tutumie Ujumbe',
    'contact.headOffice': 'Ofisi Kuu',
    'contact.officeHours': 'Masaa ya Kazi',
    'contact.responseTime': 'Tunajibu ndani ya masaa 24',
    'contact.successTitle': 'Ujumbe Umetumwa!',
    'contact.successText': 'Asante kwa kuwasiliana nasi. Tutakujibu ndani ya masaa 24.',
    // Get Involved page
    'involved.subtitle': 'Msaada wako unabadilisha maisha na kujenga jamii imara Mashariki mwa DRC',
    'involved.selectAmount': 'Chagua Kiasi',
    'involved.customAmount': 'Au Ingiza Kiasi Maalum',
    'involved.yourImpact': 'Athari Yako',
    'involved.applyVolunteer': 'Omba Kujitolea',
    'involved.partnerInquiry': 'Ombi la Ushirikiano',
    // Team page
    'team.title': 'Timu Yetu',
    'team.subtitle': 'Wataalamu waliojitolea kubadilisha maisha Mashariki mwa DRC',
    'team.leadership': 'Uongozi wa Juu',
    'team.leadershipSubtitle': 'Viongozi wenye uzoefu wanaoongoza dhamira na mwelekeo wetu',
    'team.staff': 'Timu Yetu',
    'team.staffSubtitle': 'Wataalamu wenye shauku wanaofanya kazi ardhini kuleta athari',
    'team.joinTitle': 'Jiunge na Timu Yetu',
    'team.joinText': 'Tunatafuta watu wenye shauku kujiunga na dhamira yetu',
    'team.viewPositions': 'Tazama Nafasi Zilizo Wazi',
    // Partners page
    'partners.title': 'Washirika Wetu',
    'partners.subtitle': 'Kushirikiana na mashirika duniani kote kuongeza athari Mashariki mwa DRC',
    'partners.become': 'Kuwa Mshirika',
    'partners.becomeText': 'Jiunge nasi kuunda athari ya kudumu kwa jamii za Mashariki mwa DRC',
    'partners.partnerWithUs': 'Shirikiana Nasi',
    // Forms & labels
    'form.name': 'Jina',
    'form.email': 'Barua Pepe',
    'form.phone': 'Simu',
    'form.message': 'Ujumbe',
    'form.submit': 'Wasilisha',
    'form.cancel': 'Ghairi',
    'form.quickSelect': 'Chagua Kiasi Haraka',
    'form.orEnterAmount': 'Au Ingiza Kiasi',
    'form.currency': 'Sarafu',
    'form.donateVia': 'Toa Mchango kupitia WhatsApp',
    'form.paymentDetails': 'Maelezo ya Malipo',
    'form.volunteerApp': 'Maombi ya Kujitolea',
    'form.volunteerAppDesc': 'Tafadhali jaza fomu hii kuomba kujitolea nasi.',
    'form.partnerInquiry': 'Ombi la Ushirikiano',
    'form.partnerInquiryDesc': 'Tafadhali jaza fomu hii kuomba kushirikiana nasi.',
    'form.donateTitle': 'Toa Mchango',
    'form.donateDesc': 'Tafadhali jaza fomu hii kutoa mchango.',
    'form.thankYouVolunteer': 'Asante kwa Kujitolea!',
    'form.thankYouPartner': 'Asante kwa Nia Yako!',
    'form.thankYouDonate': 'Asante kwa Mchango Wako!',
    'form.whatsapp': 'WhatsApp',
    'form.ok': 'Sawa',
    // Admin
    'admin.dashboard': 'Dashibodi',
    'admin.programs': 'Programu',
    'admin.projects': 'Miradi',
    'admin.team': 'Timu',
    'admin.partners': 'Washirika',
    'admin.news': 'Habari',
    'admin.impactStories': 'Hadithi za Athari',
    'admin.enquiries': 'Maswali',
    'admin.interests': 'Maslahi & Michango',
    'admin.about': 'Kuhusu Yaliyomo',
    'admin.settings': 'Mipangilio',
    'admin.exitAdmin': 'Ondoka Admin',
    'admin.management': 'Portali ya Usimamizi',
    'admin.addNew': 'Ongeza',
    'admin.edit': 'Hariri',
    'admin.delete': 'Futa',
    'admin.save': 'Hifadhi',
    'admin.cancel': 'Ghairi',
    'admin.search': 'Tafuta',
    'admin.refresh': 'Sasisha',
    'admin.noResults': 'Hakuna matokeo',
    'admin.confirmDelete': 'Una uhakika unataka kufuta hii?',
    'admin.programsMgmt': 'Usimamizi wa Programu',
    'admin.programsMgmtDesc': 'Simamia programu za shirika lako',
    'admin.addProgram': 'Ongeza Programu',
    'admin.teamMgmt': 'Usimamizi wa Timu',
    'admin.teamMgmtDesc': 'Simamia wanachama wa timu yako',
    'admin.addTeamMember': 'Ongeza Mwanachama',
    'admin.partnersMgmt': 'Usimamizi wa Washirika',
    'admin.partnersMgmtDesc': 'Simamia washirika wa shirika lako',
    'admin.addPartner': 'Ongeza Mshirika',
    'admin.newsMgmt': 'Usimamizi wa Habari',
    'admin.newsMgmtDesc': 'Simamia habari na makala',
    'admin.addNews': 'Ongeza Habari',
    'admin.enquiriesMgmt': 'Usimamizi wa Maswali',
    'admin.enquiriesMgmtDesc': 'Simamia mawasilisho ya fomu ya mawasiliano',
    'admin.interestsMgmt': 'Maslahi & Michango',
    'admin.interestsMgmtDesc': 'Fuatilia michango, wajitoleaji, na washirika',
    'admin.impactMgmt': 'Usimamizi wa Hadithi za Athari',
    'admin.impactMgmtDesc': 'Simamia ushuhuda na hadithi za athari',
    'admin.addStory': 'Ongeza Hadithi',
    'admin.projectsMgmt': 'Usimamizi wa Miradi',
    'admin.projectsMgmtDesc': 'Simamia miradi ya shirika lako',
    'admin.addProject': 'Ongeza Mradi',
    'admin.editProgram': 'Hariri Programu',
    'admin.addNewProgram': 'Ongeza Programu Mpya',
    'admin.programDetails': 'Maelezo ya Programu',
    'admin.programTitle': 'Jina la Programu',
    'admin.description': 'Maelezo',
    'admin.beneficiaries': 'Wanufaika',
    'admin.icon': 'Ikoni',
    'admin.publish': 'Chapisha',
    'admin.update': 'Sasisha',
    'admin.discard': 'Ondoa mabadiliko?',
    'admin.discardDesc': 'Maendeleo yote ambayo hayajahifadhiwa yatapotea.',
    'admin.deleteConfirm': 'Futa?',
    'admin.deleteDesc': 'Kipengee hiki kitaondolewa kabisa.',
    'admin.fullName': 'Jina Kamili',
    'admin.role': 'Nafasi/Cheo',
    'admin.bio': 'Wasifu',
    'admin.location': 'Mahali',
    'admin.photoUrl': 'URL ya Picha',
    'admin.teamType': 'Aina ya Timu',
    'admin.leadership': 'Uongozi',
    'admin.staff': 'Wafanyakazi',
    'admin.title': 'Kichwa',
    'admin.content': 'Maudhui',
    'admin.imageUrl': 'URL ya Picha',
    'admin.category': 'Kategoria',
    'admin.region': 'Mkoa',
    'admin.status': 'Hali',
    'admin.featured': 'Iliyoangaliwa',
    'admin.quote': 'Nukuu fupi',
    'admin.story': 'Hadithi kamili',
    'admin.personName': 'Jina la mtu',
    'admin.personRole': 'Nafasi/Maelezo',
    'admin.dash.title': 'Muhtasari wa Dashibodi',
    'admin.dash.welcome': 'Karibu tena kwenye Portali ya Admin LULA',
    'admin.dash.enquiriesToday': 'Maswali Leo',
    'admin.dash.newEnquiries': 'Maswali mapya ya mawasiliano',
    'admin.dash.interestsToday': 'Maslahi & Michango',
    'admin.dash.volunteerPartnerDonate': 'Maombi ya kujitolea, ushirikiano na michango',
    'admin.dash.totalPrograms': 'Jumla ya Programu',
    'admin.dash.activePrograms': 'Programu zinazoendelea',
    'admin.dash.totalPartners': 'Jumla ya Washirika',
    'admin.dash.orgPartners': 'Washirika wa shirika',
    'admin.dash.viewDetails': 'Tazama Maelezo',
    'admin.dash.recentContent': 'Maudhui ya Hivi Karibuni',
    'admin.dash.noContent': 'Hakuna maudhui ya hivi karibuni. Anza kwa kuongeza miradi au habari.',
    'admin.dash.quickActions': 'Hatua za Haraka',
    'admin.dash.addProject': 'Ongeza Mradi',
    'admin.dash.addNewsArticle': 'Ongeza Habari',
    'admin.dash.addPartner': 'Ongeza Mshirika',
    'admin.dash.addImpactStory': 'Ongeza Hadithi',
    'admin.aboutDesc': 'Hariri dhamira, maono, na hadithi ya shirika',
    'admin.missionStatement': 'Taarifa ya Dhamira',
    'admin.missionDesc': 'Madhumuni ya msingi ya shirika lako',
    'admin.visionStatement': 'Taarifa ya Maono',
    'admin.visionDesc': 'Malengo na mwelekeo wa baadaye wa shirika lako',
    'admin.ourStory': 'Hadithi Yetu',
    'admin.storyDesc': 'Shiriki historia na safari ya shirika lako',
    'admin.preview': 'Hakiki',
    'admin.previewDesc': 'Jinsi maudhui yako yatakavyoonekana kwenye tovuti',
    'admin.settings.account': 'Akaunti',
    'admin.settings.organization': 'Shirika',
    'admin.settings.appearance': 'Muonekano',
    'admin.settings.accountTitle': 'Mipangilio ya Akaunti',
    'admin.settings.accountDesc': 'Simamia taarifa zako binafsi na usalama',
    'admin.settings.fullName': 'Jina Kamili',
    'admin.settings.emailAddress': 'Anwani ya Barua Pepe',
    'admin.settings.changePassword': 'Badilisha Nenosiri',
    'admin.settings.currentPassword': 'Nenosiri la Sasa',
    'admin.settings.newPassword': 'Nenosiri Jipya',
    'admin.settings.confirmPassword': 'Thibitisha Nenosiri',
    'admin.settings.saveAccount': 'Hifadhi Akaunti',
    'admin.settings.orgTitle': 'Taarifa za Shirika',
    'admin.settings.orgDesc': 'Sasisha taarifa za umma za shirika lako',
    'admin.settings.orgName': 'Jina la Shirika',
    'admin.settings.acronym': 'Kifupisho',
    'admin.settings.contactEmail': 'Barua Pepe ya Mawasiliano',
    'admin.settings.phoneNumber': 'Nambari ya Simu',
    'admin.settings.website': 'Tovuti',
    'admin.settings.address': 'Anwani',
    'admin.settings.paymentDetails': 'Maelezo ya Malipo (Benki, Mobile Money, nk.)',
    'admin.settings.saveOrg': 'Hifadhi Mipangilio',
    'admin.settings.bgImages': 'Picha za Usuli',
    'admin.settings.bgImagesDesc': 'Badilisha picha za usuli za tovuti yako',
    'admin.settings.saveBg': 'Hifadhi Picha',
    'admin.settings.revert': 'Rejesha Chaguo-msingi',
    'admin.settings.viewLocation': 'Tazama Mahali',
    'admin.settings.note': 'Mabadiliko yamehifadhiwa na yanaonekana mara moja.',
    'about.value1.title': 'Huruma',
    'about.value1.desc': 'Tunaongoza kwa huruma na kujali sana jamii tunazozihudumia.',
    'about.value2.title': 'Uadilifu',
    'about.value2.desc': 'Uwazi na uwajibikaji unaongoza matendo yetu yote.',
    'about.value3.title': 'Kuzingatia Jamii',
    'about.value3.desc': 'Sauti na mahitaji ya wenyeji yanaongoza programu zetu.',
    'about.value4.title': 'Ubora',
    'about.value4.desc': 'Tunajitahidi kupata ubora wa juu katika kila tunachofanya.',
    'about.value5.title': 'Uendelevu',
    'about.value5.desc': 'Kuunda suluhisho za muda mrefu zinazoimarisha jamii.',
    'about.value6.title': 'Ubunifu',
    'about.value6.desc': 'Kukumbatia mbinu za ubunifu kwa changamoto ngumu.',
    'about.timeline1.title': 'LULA Ilianzishwa',
    'about.timeline1.desc': 'Ilianzishwa Goma kushughulikia mahitaji ya kibinadamu Kivu Kaskazini.',
    'about.timeline2.title': 'Ushirikiano wa Kwanza Mkubwa',
    'about.timeline2.desc': 'Ushirikiano na UNICEF kwa programu za ulinzi wa watoto.',
    'about.timeline3.title': 'Mpango wa Uwezeshaji Wanawake',
    'about.timeline3.desc': 'Uzinduzi wa programu za mafunzo ya ufundi kwa wanawake 5,000.',
    'about.timeline4.title': 'Upanuzi wa Elimu ya Afya',
    'about.timeline4.desc': 'Upanuzi wa kuzuia VVU na elimu ya SRH katika mikoa 12.',
    'about.timeline5.title': 'Mfuko wa Uwezeshaji Kiuchumi',
    'about.timeline5.desc': 'Uundaji wa programu ya mikopo midogo inayosaidia biashara 2,000.',
    'about.timeline6.title': 'Kufikia Wanufaika 850,000',
    'about.timeline6.desc': 'Hatua muhimu yenye athari katika Mashariki mwa DRC.',
    'news.title': 'Habari & Machapisho',
    'news.subtitle': 'Endelea kupata habari kuhusu shughuli zetu za hivi karibuni na ripoti zilizochapishwa',
    'news.searchPlaceholder': 'Tafuta habari, makala, na machapisho...',
    'news.allCategories': 'Kategoria Zote',
    'news.noResults': 'Hakuna makala yanayolingana na utafutaji wako.',
    'partners.heroTitle': 'Washirika Wetu',
    'partners.heroSubtitle': 'Kushirikiana na mashirika duniani kote kuongeza athari Mashariki mwa DRC',
    'partners.international': 'Washirika wa Kimataifa',
    'partners.internationalDesc': 'Kufanya kazi na mashirika ya kimataifa yaliyojitolea kwa athari ya kibinadamu',
    'partners.government': 'Washirika wa Serikali',
    'partners.governmentDesc': 'Kushirikiana na taasisi za serikali kwa maendeleo endelevu',
    'partners.local': 'Washirika wa Ndani',
    'partners.localDesc': 'Kujenga uhusiano imara na mashirika ya kijamii',
    'partners.collaboration': 'Maeneo ya Ushirikiano',
    'partners.collaborationDesc': 'Ushirikiano wa kimkakati katika maeneo mengi ya athari',
    'partners.activePartnerships': 'Ushirikiano Unaoendelea',
    'partners.becomeTitle': 'Kuwa Mshirika',
    'partners.becomeDesc': 'Jiunge nasi kuunda athari ya kudumu kwa jamii za Mashariki mwa DRC',
    'partners.cta': 'Shirikiana Nasi',
    'partners.programImpl': 'Utekelezaji wa Programu',
    'partners.programImplDesc': 'Utekelezaji wa pamoja wa programu za afya, elimu, na ulinzi',
    'partners.capacityBuilding': 'Kujenga Uwezo',
    'partners.capacityDesc': 'Mafunzo na msaada wa kiufundi kuimarisha mashirika ya ndani',
    'partners.research': 'Utafiti & Utetezi',
    'partners.researchDesc': 'Utafiti wa ushirikiano na utetezi wa sera kwa ulinzi wa watoto',
    'partners.resource': 'Uhamasishaji wa Rasilimali',
    'partners.resourceDesc': 'Ushirikiano wa ufadhili na ugawaji wa rasilimali',
    'involved.donateDesc': 'Mchango wako unasaidia moja kwa moja programu zetu za ulinzi wa watoto, uwezeshaji wa wanawake, na afya ya jamii.',
    'involved.volunteerDesc': 'Jiunge na timu yetu ya wajitoleaji waliojitolea wanaoleta mabadiliko.',
    'involved.partnerDesc': 'Shirikiana nasi kuongeza athari Mashariki mwa DRC.',
    'involved.thankYouVolunteerDesc': 'Tumepokea maombi yako. Timu yetu itawasiliana nawe hivi karibuni.',
    'involved.thankYouPartnerDesc': 'Tumepokea ombi lako la ushirikiano. Tutawasiliana nawe hivi karibuni.',
    'involved.thankYouDonateDesc': 'Tumepokea ombi lako la mchango. Timu yetu itawasiliana nawe na maelezo ya malipo.',
    'contact.whatsapp': 'Zungumza WhatsApp',
    'involved.supportProject': 'Unataka kusaidia mradi huu?',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      return (localStorage.getItem('lula-language') as Language) || 'en';
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('lula-language', lang);
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

// Re-export as useLULALanguage for backward compatibility
export const useLULALanguage = useLanguage;
